### ISSUE TITLE
systemd (and other service managers?) example files

### ISSUE THREAD

**Issue by cb22** [tigerbeetle/tigerbeetle#1089]
One supported way to run TigerBeetle is directly, using systemd or similar. We should provide a `.service` file with our recommended configuration.

Perhaps for some other common service managers too. Mildly related to a larger project of providing Helm charts for TigerBeetle.

**Comment by pragmaticanon** [comment]
Hey @cb22 would love to take this on if that's okay. Would be great if you could provide with some of your initial thoughts and I'll build on it

**Comment by cb22** [comment]
Sure! 

I was thinking something along the lines of a basic `systemd` unit file, with an `EnvironmentFile` of eg `/etc/conf.d/tigerbeetle`. This could then have in what are normally CLI flags:

```
CLUSTER=123
REPLICA=0
REPLICA_COUNT=3
ADDRESSES=1.2.3.4:3000,1.2.3.5:3000,1.2.3.6:3000
CACHE_GRID=1GB
DATAFILE=/var/db/tigerbeetle/data.tigerbeetle
```

Then, those can be referenced within the `ExecStart` of the unit file, eg:
`ExecStart=/usr/bin/tigerbeetle ... --addresses=${ADDRESSES} ${DATAFILE}`

We can also have an `ExecStartPre` that formats `DATAFILE` if it doesn't exist (should be pretty safe, since we'd have both systemd checking it doesn't exist, and TigerBeetle will refuse to format an existing file.

Lastly, we can add some restart stuff so it auto-restarts in case of failure (https://www.redhat.com/sysadmin/systemd-automate-recovery).

That should be a good starting point, let me know if you have any other questions :smile:

**Comment by pragmaticanon** [comment]
Yeah that sounds good, any thoughts on helm charts and if this is a good point to start working on it?

**Comment by DanielSidhion** [comment]
@pragmaticanon did you make any progress on this? I'm considering creating a NixOS module for tigerbeetle and would like to reuse any work if possible. If not, I'll just figure out the proper config values and can contribute some example files back.
