### ISSUE TITLE
Protocol and storage format under active development

### ISSUE THREAD

**Issue by cb22** [tigerbeetle/tigerbeetle#1109]
While still under active development, we may make changes that break the protocol and storage format at any time. It's strongly recommended that if you're experimenting with TigerBeetle you:

- Use a freshly formatted data file for the commit you've built or installed.
- Only run replicas of the same version in a cluster.
- Use the identical matching client version.

**Comment by darcythomas** [comment]
_This may be too soon to ask:_

**Nice to have:**

A policy that the wire protocol and the storage format are not changed in the same commit/release.
(Or have a backwards compatibility by version -1 of the protocol)

Then we could build some migration tooling to upgrade a cluster between commits/releases.


This may come under: "**StateMachine: Add bulk-import path for data (including timestamps). (Probably need a CLI for this too.)**"

**Comment by sentientwaffle** [comment]
Hi @darcythomas,

> A policy that the wire protocol and the storage format are not changed in the same commit/release.
> (Or have a backwards compatibility by version -1 of the protocol)

Certain changes to the wire protocol will necessarily impact the storage format. (That is to say, if you upgrade from version X to version X+1, then you are not subsequently able to downgrade to version X).

That said, the version X clients will still be compatible with the version X+1 cluster, so clients can be upgraded to X+1 later on at your convenience.

"migration tooling" (in the sense that ORMs use the term "migration"; lmk if you meant differently) won't be necessary; the cluster will be able to keep reading its old data without needing to rewrite it all.

This isn't implemented yet, but will be implemented prior to our 1.0 release.

**Comment by matklad** [comment]
We have storage stability and upgrade story implemented.
