### ISSUE TITLE
Fast historical balance queries

### ISSUE THREAD

**Issue by bergkvist** [tigerbeetle/tigerbeetle#1115]
It seems like tigerbeetle is optimised for inserts rather than analytical queries.

I believe for smaller scale hobby projects or startups, the 1M TPS is not going to matter much, and the latency of analytical queries would be much more important than insert throughput. At a very small scale, running a separate analytical database might also not make sense from a cost and complexity perspective.

In particular - allowing a user to view historical account balances at different resolutions is something I imagine would be a very typical use case for investment banks, funds etc. (so that it can be plotted on a web frontend)

**Comment by jorangreef** [comment]
Thanks @bergkvist — agreed on all these points, and for the same reasons.

We're already working on the LSM Scans infrastructure to support fast historical balance queries. Watch this space!

Let me know also if you'd like to bounce ideas on a call on this and other queries. Feel free to DM me in our community Slack.

**Comment by matklad** [comment]
Closed by https://github.com/tigerbeetle/tigerbeetle/pull/1526 I would thing
