### ISSUE TITLE
REPL: `lookup_accounts` error should be similar to `create_accounts` error

### ISSUE THREAD

**Issue by cb22** [tigerbeetle/tigerbeetle#1184]
When calling `create_accounts` to raise an error, it exposes the internal enum, which is what we want:

```
> create_accounts id=1 code=10 ledger=700;
Failed to create account (0): tigerbeetle.CreateAccountResult.exists.
```

When calling `lookup_accounts` it prints something different:
```
> lookup_accounts id=555;
No such account or accounts exists.
```

**Comment by ReppCodes** [comment]
If nobody minds, I'd like to take a shot at this one to start out!

**Comment by cb22** [comment]
Sorry @ReppCodes I realized some people may not get notifications for reactions - that's great, please go ahead :rocket:

**Comment by ReppCodes** [comment]
Ah, awesome thanks.  I'll dig in!

**Comment by ReppCodes** [comment]
Opened PR to address: https://github.com/tigerbeetle/tigerbeetle/pull/1195
