### ISSUE TITLE
ManifestLevel iterator can't find invisible tables.

### ISSUE THREAD

**Issue by kprotty** [tigerbeetle/tigerbeetle#1193]
The following code is a set of manifest calls that seem to happen within a Tree compaction measure when moving values from Immutable into Level 0:

```zig
// half_beat_end
manifest.insert_table(0, &.{
    .checksum = 0,
    .address = 0xdeadbeef,
    .snapshot_min = 8,
    .key_min = 42,
    .key_max = 1337,
});
manifest.remove_invisible_tables(0, snapshot_latest, 42, 1337);
// checkpoint
manifest.assert_level_table_counts();
manifest.assert_no_invisible_tables(6);
```

Notice that the table is inserted with `snapshot(min=8, max=INT_MAX)` which is visible to `snapshot_latest` on the next line so it's not removed. The problem arises with `assert_no_invisible_tables` being given a snapshot that's smaller than the `snapshot_min` used to create the table. It should detect that (6) is outside the table's snapshot range and error having found one invisible, but the current implementation does not detect it and keeps running.

Repro: https://gist.github.com/kprotty/c5d7e95959508d27420a38bb159b8b55

**Comment by sentientwaffle** [comment]
If the table is visible to `snapshot_latest`, then we assume that it is definitely not invisible:

```zig
        pub fn invisible(table: *const TreeTableInfo, snapshots: []const u64) bool {
            // Return early and do not iterate all snapshots if the table was never deleted:
            if (table.visible(snapshot_latest)) return false;
```

**Comment by kprotty** [comment]
Ah, didn't notice the semantic difference between `table.visible()` and `table.invisible()`. In the former, a table can be "invisible" if outside the snapshot range even if inside the `snapshot_latest` range.
