### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by borgoat** [tigerbeetle/tigerbeetle#1211]
Hello TigerBeetle team!

I'm trying out something, running TB on fly.io. They offer IPv6-only instances out of the box.

Alternatively, one may pay 2 USD/month for a dedicated IPv4 address![^2] And the docs make it sound like it's not even pro-rated. 😱

Shared v4 addresses could also be an option, assuming TLS was used, but I know from #259 that this is anyway in the roadmap.

Having said that, I was therefore wondering about IPv6 support... I see throughout the codebase that IPv4 is always explicitly used, and have the feeling that it wouldn't take a lot of work to swap them to use alternative implementations, the Zig docs suggest for example to use `resolveIp` to cover both cases instead of `parseIp`[^3]. But I guess I may be missing something? I see tests always assume IPv4 too, so clearly this is not just an issue when parsing the CLI string...

Does this have something to do with the VSR proto internals? Or because of how memory allocation is handled?

[^1]: https://fly.io
[^2]: https://fly.io/docs/about/pricing/#anycast-ip-addresses
[^3]: https://ziglang.org/documentation/master/std/#A;std:net.Address.parseIp

**Comment by cb22** [comment]
Hey @borgoat :wave: 

You're not missing anything; it's just something we haven't gotten around to yet! We do intend to support IPv6, likely as part of #74. (I even had a very old branch that had DNS resolution working, for both v4 and v6 at one point. There's then a bit more around parsing the CLI args, but that's mostly it.)

**Comment by sentientwaffle** [comment]
@borgoat:

https://github.com/tigerbeetle/tigerbeetle/pull/1212 just merged, so you can pass ipv6 addresses now, e.g.:

```
--addresses='[::1]:3003,[::1]:3001,[::1]:3002'
```

Let me know if it gives you any trouble!

**Comment by borgoat** [comment]
Hey, that was fast! Thanks!
The connection seems to work. At least on localhost it does work 100%.

I'm getting some unrelated error on the fly deployment coming from the message bus, complaining that the queue is full, but I'll figure it out!

**Comment by sentientwaffle** [comment]
If you build the server with  ` -Dconfig-log-level=debug`, that might help too!

If those message bus errors are on the client, then it might be that the client cannot connect to the server.

**Comment by jorangreef** [comment]
Hey @borgoat 👋 ⛷️ did you have luck figuring out the message bus error on Fly?

**Comment by borgoat** [comment]
Hey @jorangreef! Not yet unfortunately... I'm now getting my sailing licence, and there goes the little free time I had left ¯\_(ツ)_/¯

I do know from a Wireshark capture however that this is all caused by a TCP reset, TigerBeetle logs nothing at all, even with `-Dconfig-log-level=debug`, so I tend to believe this is coming from the Fly proxy and/or Wireguard tunnel. It should let TCP pass-through, but maybe something else is happening behind the scenes. I'll investigate further when I get the chance 😎

**Comment by jorangreef** [comment]
Haha, that's awesome to hear. I thought you had your sailing license for a long time by now!

I believe we treat the TCP reset as a connection close (would you prefer we error log this?). Or we could flag this using metrics rather, to avoid spamming the logs?

**Comment by borgoat** [comment]
Well I've been sailing since a long time, but I am now getting licenced to actually skipper a boat! ⛵ 

The thing is that the client just logs that the peer shut down the connection[^1], while in reality this is not even coming from TigerBeetle.
From a user POV I'm wondering if it'd be more useful to have a first message the moment the client starts, rather than when it tries to send a first transaction/create account, to know if the connection could be established or not.

I'm not sure if that makes sense.

[^1]: ["peer performed an orderly shutdown"](https://github.com/tigerbeetle/tigerbeetle/blob/ca9c09556635347c95d2345bfb02155ef82b1806/src/message_bus.zig#L932)

**Comment by jorangreef** [comment]
> Well I've been sailing since a long time, but I am now getting licenced to actually skipper a boat! ⛵

Bellagio!

> The thing is that the client just logs that the peer shut down the connection[1](https://github.com/tigerbeetle/tigerbeetle/issues/1211#user-content-fn-1-3f33d5f6a305aa027772093226c990cf), while in reality this is not even coming from TigerBeetle.

Yes, we don't distinguish here between the peer and middleware.

> From a user POV I'm wondering if it'd be more useful to have a first message the moment the client starts, rather than when it tries to send a first transaction/create account, to know if the connection could be established or not.

I wanted to keep the message passing layer separate from (and above) the underlying connection transport layer, and also to avoid any connection handshake as far as possible, to avoid introducing state. This means a client can send a request message to a primary (which replicates before crashing), and then get a response message back from the new primary. So a client may be logically connected to the cluster, while perhaps not physically connected to all machines in the cluster.

However, I understand the surprise. We do have ping/pong messages that we could perhaps leverage here, to surface whether there is any connectivity. I don't know if increasing surface area like that is preferable to trying to send a request and seeing that a response is not coming back? The former might seem like connectivity information, but it's hard to tell without actually sending an actual request, when it needs to be sent? We're definitely thinking about this now...

**Comment by borgoat** [comment]
Yeah I was also thinking of something like a ping/pong message, being sent immediately by the client when connecting.

I think this is a small detail, that offers however a much better experience for any TigerBeetle user. It doesn't mix layers on the server, it is stateless, but it does give some peace of mind to the operator, knowing that the transport layer is working, and they're getting an actual response by the service. It's useful when initially configuring a new downstream service (fixing firewalls, security groups, and similar), but potentially for a circuit-breaker too.

This is probably even more important once auth is there: sure it may be for instance handled by mTLS, but how do we know if TigerBeetle is happy about the user claims before they get a message back from it? Knowing the transport layer works may not be enough.

I am also curious about another point though:

> [...] a client can send a request message to a primary (which replicates before crashing), and then get a response message back from the new primary.

I can see that working on top of UDP (although that would mean sharing the destination with the rest of the cluster leaking some transport layer info). Whereas on TCP... not so easily, without spoofing at least. 😋 Is there something interesting in the works here, or did I misunderstand your statement?

**Comment by jorangreef** [comment]
> I am also curious about another point though [...] I can see that working on top of UDP (although that would mean sharing the destination with the rest of the cluster leaking some transport layer info). Whereas on TCP... not so easily, without spoofing at least. 😋 Is there something interesting in the works here, or did I misunderstand your statement?

Yes, I think this difference gets to the heart of the matter:

TigerBeetle's networking is in fact message-based, not connection-based.

Whether the MessageBus (under the hood) uses a connection-oriented protocol such as TCP (each client then connects to all replicas, to enable the optimization I described above) or a message-oriented protocol such as UDP, is implementation. Hence, I am not sure that we should expose a "connected" state at the interface of the MessageBus, since the interface is designed explicitly not to be connection-oriented, to support more underlying transport protocols.

We could add a feature to diagnose the ability to send a message from a client to some replicas in the cluster (logically) or to all replicas in the cluster (physically), but I am not sure if this is orthogonal to network diagnostics already available at the CLI?

(I want to be wary about increasing surface area, if we could not provide pointers instead to a way to do this at the CLI).
