### ISSUE TITLE
link in DESIGN.md is broken

### ISSUE THREAD

**Issue by bronze1man** [tigerbeetle/tigerbeetle#1238]
the page is https://github.com/tigerbeetle/tigerbeetle/blob/main/docs/DESIGN.md
the link is https://www.tigerbeetle.com/post/three-clocks-are-better-than-one
the right looks like https://tigerbeetle.com/blog/three-clocks-are-better-than-one/

**Comment by jorangreef** [comment]
Thanks @bronze1man!

You're right. Would you like to do a small PR?
