### ISSUE TITLE
Rework build.zig and shorten our CI script

### ISSUE THREAD

**Issue by matklad** [tigerbeetle/tigerbeetle#1280]
Our build.zig and .yml workflows accrued quite a bit of cruft. I haven't yet reached the critical mass of annoyance  to go and clean this all up, but I'd love to document some ideas of what could be improved:

1. Centralize few top-level steps for common workflows:

   * `zig build test` for unit-tests
   * `zig build check` for quick pre-commit checks (compile all binaries (without codegen if possible), check formatting, run tidy).
   * `zig build fuzz` as a unified frontend for fuzzing
   * `zig build benchmark` ditto for benches
   * `zig build ci` to run everything that CI does (so, all of the above), use that from .yml

2. Cut down on the number of build.zig targets altogether. Most notably, don't do a separate binary for each unit-fuzzer. Things like `repl_integration` also feel like they should be moved elsewhere, so that each new `xxxx_integration` does not require changing build.zig or linux.yml.
3. Consistently name targets: `simulator`, `simulator:build`, `fuzz`, `fuzz:build`
4. Just in general, shorten build.zig. We shouldn't need 1kloc of logic to build tigerbeetle, it is supposed to be simple&small! 
5. Revive mac and windows tests
6. Try to get rid of `builder_with_isolated_cache`
7. Use `-Drelease` / `-Ddebug` instead of `-Doptimize`
8. Get rid of `ldd: warning: you do not have execution permission for` warning (but, ideally, find non-hacky way to build java)

One important overarching goal: adding new things to TigerBeetle should not require changing build.zig or .yml. Those should be fixed, and new additions should only touch zig files.

**Comment by jorangreef** [comment]
Agree ^ 8 (and love the `zig build check` step, all the names, and the cutting down of targets altogether).
