### ISSUE TITLE
Node library throws unhelpful error if your `code`s are too big

### ISSUE THREAD

**Issue by emschwartz** [tigerbeetle/tigerbeetle#1290]
If you submit an `Account` or `Transfer` with a `code` that's bigger than a 16-bit integer, the library will throw an unhelpful error:

```
tigerbeetle-schema-gen/node_modules/tigerbeetle-node/dist/index.js:59
                binding.submit(context, operation, batch, (error, result) => {
                        ^

Error: code
    at tigerbeetle-schema-gen/node_modules/tigerbeetle-node/dist/index.js:59:25
    at new Promise (<anonymous>)
    at request (tigerbeetle-schema-gen/node_modules/tigerbeetle-node/dist/index.js:57:16)
    at Object.createAccounts (tigerbeetle-schema-gen/node_modules/tigerbeetle-node/dist/index.js:77:40)
    at file:///tigerbeetle-schema-gen/dist/index.js:23:34
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.17.1
```

It would be useful for the library to check the sizes of integer fields and return specific errors if you exceed the allowable size.

**Comment by batiati** [comment]
We already have a test for it in place (and it's correctly failing).
For some reason, it's not running during CI.
cc @matklad 

https://github.com/tigerbeetle/tigerbeetle/blob/9871760c8567760271d34afde9e67039bb30569b/src/clients/node/src/test.ts#L58-L67

**Comment by matklad** [comment]
Yeah, I don't think we've ever run those tests on CI?

There's placeholder place for them over here, it's high time we sort this out:

https://github.com/tigerbeetle/tigerbeetle/blob/9871760c8567760271d34afde9e67039bb30569b/src/clients/node/ci.zig#L14
