### ISSUE TITLE
Better docker shutdown behaviour

### ISSUE THREAD

**Issue by matdehaast** [tigerbeetle/tigerbeetle#136]
Currently when shutting down  tigerbeetle in docker is a slow process. I think TB needs to better handle sigint/sigterm which  could correspond to better shutdown modes. Here is an comment from the postgres docker image

> We set the default STOPSIGNAL to SIGINT, which corresponds to what PostgreSQL
calls "Fast Shutdown mode" wherein new connections are disallowed and any
in-progress transactions are aborted, allowing PostgreSQL to stop cleanly and
flush tables to disk, which is the best compromise available to avoid data
corruption.
Users who know their applications do not keep open long-lived idle connections
may way to use a value of SIGTERM instead, which corresponds to "Smart
Shutdown mode" in which any existing sessions are allowed to finish and the
server stops when all sessions are terminated.
See https://www.postgresql.org/docs/12/server-shutdown.html for more details
about available PostgreSQL server shutdown signals.
See also https://www.postgresql.org/docs/12/server-start.html for further
justification of this as the default value, namely that the example (and
shipped) systemd service files use the "Fast Shutdown mode" for service
termination.

**Comment by jorangreef** [comment]
Thanks @matdehaast 

Can you provide more context?

It looks like Postgres uses `SIGINT` to “stop cleanly and flush tables to disk [..] to avoid data corruption”, which does not apply to TB. You can crash TB safely at any time, as quickly as you like. You shouldn't need to be waiting on anything?

**Comment by jorangreef** [comment]
TB also does not need Postgres' “Smart Shutdown mode”, which Postgres uses to delay shutdown until existing sessions are finished—since the new primary will simply complete the work that the terminating primary was doing, and the new primary will reply directly back to those existing sessions. So again, shutdown with TB should always be instantaneous.

I don't know if Docker is doing something to delay shutdown?

**Comment by matdehaast** [comment]
Thanks @jorangreef. So from my current understand of using TB, when I try kill a docker tigerbeetle it doesn't actually crash. It hits the docker timeout before hard killing it. Which is 20s. It would be nice for it to exit quicker if I kill the docker instance. It may be just the way that is configured to be passed to the TB process? Not sure

**Comment by jorangreef** [comment]
Do you know what signal Docker is sending the TB process? It's probably sending us something very polite :)

Update: Also, confirming that you are using `docker stop ...`? You should probably see no delay if you use `docker kill ...`?

**Comment by jorangreef** [comment]
Looks like it's first sending us `SIGTERM` and then waiting and then sending us `SIGKILL`, right?

**Comment by jorangreef** [comment]
@kprotty would you be able to handle `SIGTERM` for us, so that it also kills the TB process?

**Comment by matdehaast** [comment]
Alternatively we could just change the dockerfile default to `SIGKILL`

```
STOPSIGNAL SIGKILL
```

**Comment by DXist** [comment]
Will it make sense to proactively initiate view/leader change if a leader is going to be shut down?

Ideally it should result in lower request serving tail latency during the transition period.

**Comment by matklad** [comment]
Closed by https://github.com/tigerbeetle/tigerbeetle/pull/1813
