### ISSUE TITLE
Allow primaries with a dirty journal

### ISSUE THREAD

**Issue by matklad** [tigerbeetle/tigerbeetle#1378]
Before state sync, we had an invariant that only a replica with a pristine log can become primary:

https://github.com/tigerbeetle/tigerbeetle/blob/b4caaa510ec37f6e9ad9227bd557dc6c59a008e2/src/vsr/replica.zig#L5480

After the state sync, it might be the case that it's impossible for the primary to repair its entire log, as the cluster state beyond the checkpoint is not available. We need to fix it:

* add replica_test tests around this area
* unify the logic between the primary and the backup and just never repair beyond checkpoint:
   https://github.com/tigerbeetle/tigerbeetle/blob/b4caaa510ec37f6e9ad9227bd557dc6c59a008e2/src/vsr/replica.zig#L5122
* allow primary to start view even if it has some dirty entries in the journal. commit_min=commit_max+pristine pipeline should be enough

**Comment by sentientwaffle** [comment]
There is also "repair-min" logic in `Replica.on_repair_sync_timeout()` that will probably need a similar update.

A backup tries to infer the _primary's_ `op_repair_min` via `commit_max` and the currently known highest-canonical-checkpoint. Based on this repair-min, it decides whether or not it is "stuck" -- i.e., will be able to repair its WAL (this is ideal), or should it fall back to state sync.
