### ISSUE TITLE
voprhub: Check non-main seed on main

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#1492]
The voprhub mostly runs against `main`, but can test non-`main` branches (when PR's are tagged with `vopr`).

When the voprhub discovers a broken seed on a non-`main` branch, before creating a github issue for that seed, it should test the seed on `main`. If the seed _also_ fails on `main`, it should specify that instead of the non-`main` branch in the PR description.

(Inspired by https://github.com/tigerbeetle/tigerbeetle/issues/1484)

**Comment by jorangreef** [comment]
Great idea.

**Comment by matklad** [comment]
Probably not worth extra complexity and the loss of robustness here. The actual problem is solved by not having failing seeds on main, which we are at 99% for!
