### ISSUE TITLE
MessageBus should verify message aligment

### ISSUE THREAD

**Issue by matklad** [tigerbeetle/tigerbeetle#1518]
https://github.com/tigerbeetle/tigerbeetle/blob/78be5cb1ab0e48a0d1a791ba922b79a8e8396469/src/message_bus.zig#L712

As far as I can tell, this `@alignCast` can fire: we never check that `header.size` is a multiple of `@sizeOf(u256)`.

**Comment by sentientwaffle** [comment]
If we resolve this by relaxing the message body alignment requirement, https://github.com/tigerbeetle/tigerbeetle/pull/1670/commits/5beb02c86efd250249b16950297b339b712472d0 can be reverted.

**Comment by sentientwaffle** [comment]
Per slack discussion: `src/message_bus.zig` can just send some extra (padding, zeroed) bytes beyond `message.size` over the transport to ensure that the decoding-end always ends up with a header-aligned message on the boundary.

**Comment by matklad** [comment]
>>Per slack discussion: src/message_bus.zig can just send some extra (padding, zeroed) bytes beyond message.size over the transport to ensure that the decoding-end always ends up with a header-aligned message on the boundary.

And the reason for that is that our messages _already_ are not guaranteed to be aligned. In particular, state machine reply can be a single `CreateAccountsResult`, and `@sizeOf(CreateAccountsResult) == 8`
