### ISSUE TITLE
Unzip error in the bootstrap.ps1 script [Error][Windows]

### ISSUE THREAD

**Issue by felipevalerio** [tigerbeetle/tigerbeetle#1586]
**Situation:** When I try to prebuild a copy of TigerbeetleDB on Windows it gives me this error when I  run the ./bootstrap.ps1 command

Looking at the code I see that the script uses unzip but Powershell doesn't recognize this command as you can see in the picture below:

![unzip_error](https://github.com/tigerbeetle/tigerbeetle/assets/33168249/539dd04e-e047-4bdb-a467-861554186c08)

**Error:** Its in Portuguese but transalated it means: unzip: "The term 'unzip' is not recognized as the name of an operable cmdlet, function, script file, or program."

**Solution:** I replaced this command for a Powershell command that does the same thing: "Expand-Archive" (https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-7.4)

After that I could run the script and follow the instructions to create a replica and so on.

**Sugestion:** make an official replacement of the "unzip" command for the "Expand-Archive" for the Windows Plataform.

**Comment by Petterrolvag** [comment]
I just want to confirm that this also happens for me on Windows 11, and that I was able to fix it in the same way.

**Comment by felipevalerio** [comment]
Nice! I forgot to mention that I tested on Windows 10.
