### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by RealZimboGuy** [tigerbeetle/tigerbeetle#1592]
attempting to run 

     ./tigerbeetle format --cluster=0 --replica=0 --replica-count=1 0_0.tigerbeetle

dont see any other info, maybe if you have a docker image it could be a nice easy way to spin up an instance ?

 cat /etc/os-release

        NAME="Linux Mint"
        VERSION="20.3 (Una)"
        ID=linuxmint
        ID_LIKE=ubuntu
        PRETTY_NAME="Linux Mint 20.3"
        VERSION_ID="20.3"
        HOME_URL="https://www.linuxmint.com/"
        SUPPORT_URL="https://forums.linuxmint.com/"
        BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
        PRIVACY_POLICY_URL="https://www.linuxmint.com/"
        VERSION_CODENAME=una
        UBUNTU_CODENAME=focal

**Comment by sentientwaffle** [comment]
Hi @RealZimboGuy,

We do have a docker image; see: https://docs.tigerbeetle.com/quick-start/with-docker for details.

Can you paste the output of:

- `./tigerbeetle version --verbose`
- `sha256sum ./tigerbeetle`
- `cat /proc/cpuinfo | head -n28`

Thanks!

**Comment by RealZimboGuy** [comment]
./tigerbeetle version --verbose
        Illegal instruction (core dumped)
 
        sha256sum ./tigerbeetle
        f692ca17fb97f235d6db61b20ce7a0b6ae3aaee9c7d6f341eabfcdb2d0fcb0b0  ./tigerbeetle

        cat /proc/cpuinfo | head -n28
        processor	: 0
        vendor_id	: GenuineIntel
        cpu family	: 6
        model		: 42
        model name	: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
        stepping	: 7
        microcode	: 0x2f
        cpu MHz		: 900.000
        cache size	: 6144 KB
        physical id	: 0
        siblings	: 8
        core id		: 0
        cpu cores	: 4
        apicid		: 0
        initial apicid	: 0
        fpu		: yes
        fpu_exception	: yes
        cpuid level	: 13
        wp		: yes
        flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
        vmx flags	: vnmi preemption_timer invvpid ept_x_only flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest
        bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
        bogomips	: 4390.18
        clflush size	: 64
        cache_alignment	: 64
        address sizes	: 36 bits physical, 48 bits virtual
        power management:

**Comment by RealZimboGuy** [comment]
running the docker command 

    docker run -p 3000:3000 -v $(pwd)/data:/data ghcr.io/tigerbeetle/tigerbeetle  start --addresses=0.0.0.0:3000 /data/0_0.tigerbeetle

the cli just exits with no output

**Comment by sentientwaffle** [comment]
Our binaries depend on some CPU features (e.g. hardware-accelerated AES) that your machine is missing.

Switching to a newer CPU would work :sweat_smile: (~2014 or newer).
Alternatively, you can compile without support for those CPU features.

If you clone the repo, you can apply this patch:

```
diff --git a/build.zig b/build.zig
index 99b0246a8..369f01b08 100644
--- a/build.zig
+++ b/build.zig
@@ -18,17 +18,17 @@ const supported_targets: []const CrossTarget = supported_targets: {
         "aarch64-macos",
         "x86_64-linux",
         "x86_64-macos",
         "x86_64-windows",
     };
     const cpus = .{
         "baseline+aes+neon",
         "baseline+aes+neon",
-        "x86_64_v3+aes",
+        "baseline",
         "x86_64_v3+aes",
         "x86_64_v3+aes",
     };
     for (triples, cpus) |triple, cpu| {
         result = result ++ .{CrossTarget.parse(.{
             .arch_os_abi = triple,
             .cpu_features = cpu,
         }) catch unreachable};
```

and then run `zig build -Drelease` to compile. Likewise you'll have to rebuild the client (instructions there depend on which language client you plan on using).

**Comment by RealZimboGuy** [comment]
will give it a try on my other pc tomorrow, thanks

**Comment by RealZimboGuy** [comment]
works fine on newer cpu

**Comment by andymarden** [comment]
For anyone else looking for this - as of the latest release of tigerbeetle, you also need to comment out this line:
```
assert(std.crypto.core.aes.has_hardware_support);
```
in src/vsr/checksum.zig
