### ISSUE TITLE
who uses tigerbeetle and what is it used for?

### ISSUE THREAD

**Issue by ouvaa** [tigerbeetle/tigerbeetle#1604]
1. what's the use case of tigerbeetle? (seems like for a bank but doesnt seem so too)
2. how to do multi datacenter replication?

**Comment by longmauriceproj** [comment]
Have you had a chance to go through the documentation? They answer the question of what problem this database is intended to solve. The [History](https://github.com/tigerbeetle/tigerbeetle/blob/main/docs/HISTORY.md) and [Design](https://github.com/tigerbeetle/tigerbeetle/blob/main/docs/DESIGN.md) markdown files are good places to start.

**Comment by matklad** [comment]
This is generally answered in our docs: https://docs.tigerbeetle.com

1. This is a database for accounting, primarily, but not only, financial accounting. 
2. The recommended setup is to have a cluster of 6 replicas, 2 replicas per availability zone

I understand that our docs are not in the best shape right now, and it indeed might be hard to get the big picture, but we are working on overhauling the docs right now!
