### ISSUE TITLE
Are there plans to make the engine embeddable?

### ISSUE THREAD

**Issue by rouzier** [tigerbeetle/tigerbeetle#1613]

**Comment by matklad** [comment]
Certainly! Not only TigerBeetle is fast, it is also small. In the code, we implement and test "solo" mode, which is intended for embeddable use-cases:

https://github.com/tigerbeetle/tigerbeetle/blob/55a6ca0b4471e0a3e976ee714aa119437d452bbd/src/vsr/replica.zig#L4871

Though, embedded databas is not our primary use-case. We'll get there one day, but probably not in the nearest future.
