### ISSUE TITLE
REPL : history of commands and up and down arrows

### ISSUE THREAD

**Issue by jalotra** [tigerbeetle/tigerbeetle#1644]
what ? 
- add support for arrows to see history and run past commands., just like unix 
- right now it is not implemented.

<img width="755" alt="image" src="https://github.com/tigerbeetle/tigerbeetle/assets/39359593/43a6207f-5001-4b69-a68e-796174594224">

**Comment by jalotra** [comment]
nvm, duplicate of #1183

**Comment by matklad** [comment]
Thanks for finding the dup @jalotra!
