### ISSUE TITLE
Java client jar includes Benchmark code

### ISSUE THREAD

**Issue by ddebree** [tigerbeetle/tigerbeetle#1658]
The java client includes the Benchmark code as part of the downloaded jar. 
While it may be useful for someone testing out the client jar to have the code immediately available, it does mean that the complete classpath of the application would include more than one `public static void main` method (one in the client jar and another in the client application). A compiled app would likely ignore the second psvm method, but it seems weird that it is there. 
Perhaps the Benchmark code could be moved to the src/test folder?

**Comment by batiati** [comment]
Hello @ddebree!
Indeed it should not be packed in the same jar! Thanks for reporting.

**Comment by ddebree** [comment]
Happy to submit a PR if you want to assign it to me?

**Comment by batiati** [comment]
> Happy to submit a PR if you want to assign it to me? 

Sure! It's a pleasure to have your contribution!

For context, this benchmark code can be completely removed among the benchmark.sh script in the Java client's folder.
It was inherited from the time we had separate repository for each client.

Also, currently our official benchmark runs a workload very different, so there's no point keeping this old one for comparison. We have plans for something special for testing and benchmarking the various clients
