### ISSUE TITLE
scripts/benchmark.sh was broken by dc45c90c759dd754d8fbbe896f901d462736a2de

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#167]
Before dc45c90c759dd754d8fbbe896f901d462736a2de the benchmark completes successfully. Afterwards it gets stuck at https://github.com/tigerbeetledb/tigerbeetle/blob/156b04750626d5fd11f017b5bfb9c2858c983926/src/vsr/replica.zig#L5466 because storage.tick() is now a noop.

**Comment by jorangreef** [comment]
This also breaks our `format` command.

CC @sentientwaffle and @kprotty

**Comment by kprotty** [comment]
`storage.tick` was made to be a no-op from the referenced commit as its now recommended to `io.tick` directly instead. We could try removing `storage.tick` and see where it's used.

**Comment by sentientwaffle** [comment]
@kprotty was this fixed by https://github.com/tigerbeetledb/tigerbeetle/pull/169?

**Comment by kprotty** [comment]
Yep
