### ISSUE TITLE
In ByteSize type, do not parse "MB", "GB" etc.

### ISSUE THREAD

**Issue by brson** [tigerbeetle/tigerbeetle#1673]
In our flags parser for the `ByteSize` type we treat "MB" and "MiB", etc. the same - as powers of 2 units. Per discussion in https://github.com/tigerbeetle/tigerbeetle/pull/1565 and elsewhere I believe we prefer to be pedantic about these units, and since it may be confusing to parse "MB" as a power of 10 that we should just not support it at all.

Change the ByteSize parser to remove support for "KB", "MB", "GB" etc.

Related to https://github.com/tigerbeetle/tigerbeetle/issues/1672

cc @jorangreef I think this is your preference (vs. supporting the units with the pedantically correct values).

**Comment by brson** [comment]
It will be worth looking at the CLI help messages and other docs related to these flags and making sure it is obvious to the user what units they accept.

i.e. if the user _does_ try to use "MB", maybe there needs to be an explicit error saying to use "MiB" instead.

**Comment by samarth-jain28** [comment]
hey, I am new to contributions, I saw this "good first" issue, and I wanted to contribute to it. 
Can you guide me .

**Comment by srpcoder** [comment]
Hi there,
Worked on the typos. Kindly review my PR

**Comment by brson** [comment]
@samarth-jain28 It looks like this already has a pr submitted for it here: https://github.com/tigerbeetle/tigerbeetle/pull/1674

**Comment by brson** [comment]
Fixed by https://github.com/tigerbeetle/tigerbeetle/pull/1674
