### ISSUE TITLE
Question: Publish/broadcast and/or push capability

### ISSUE THREAD

**Issue by unibum** [tigerbeetle/tigerbeetle#1838]
Hello
,
Apologies for question here.

1) Is there a capability to push a message/notification when the balance gets to 0? e.g. Use TigerBeetle for counting stock/inventory (decrementing) and when a particular stock item gets to e.g. 0, then pushing a notification to a cache or web page with this information?

Also,
2) Is there a broadcast capability that one or multiple users can subscribe to a inventory items balance and get pushed new values as they change? E.g. a page may be subscribing to 100 or more balances and could be millions of users with any given combinations of products on screens showing real time balances (stock items remaining).

Want to understand if capabilities exist, and if theres any limitation to scaling as in number of balances internally that can be monitored and max number of subscribes etc as well.. what would the first bottleneck be before we have to spin up a 2nd instance etc..

Thank you.

**Comment by sentientwaffle** [comment]
Thanks for the questions!

> 1. Is there a capability to push a message/notification when the balance gets to 0? e.g. Use TigerBeetle for counting stock/inventory (decrementing) and when a particular stock item gets to e.g. 0, then pushing a notification to a cache or web page with this information?

TigerBeetle doesn't have any broadcast/event system, but you can implement this feature in your application by building atop TigerBeetle's primitives.

First, for counting inventory, the account would have one of the balance limit flags set ([`flags.debits_must_not_exceed_credits`](https://docs.tigerbeetle.com/reference/accounts#flagsdebits_must_not_exceed_credits) or [`flags.credits_must_not_exceed_debits`](https://docs.tigerbeetle.com/reference/accounts#flagscredits_must_not_exceed_debits)) to ensure that the inventory account's balance is non-negative.

When you remove items out of the inventory, you would use a [linked](https://docs.tigerbeetle.com/develop/client-requests/#linked-events) sequence of transfers like this:

```
// Transfer A tries to move a single item out of the inventory...:
{ id = A, debit_account_id = (inventory account), credit_account_id = (control account), amount = 1, linked = true }
// ...And then transfer B puts the item back, so that the inventory is untouched:
{ id = B, debit_account_id = (control account), credit_account_id = (inventory account), amount = 1, linked }
// Finally, transfer C moves items out of the inventory to their destination:
{ id = C, debit_account_id = (inventory account), credit_account_id = (destination account), amount = (number of items) }
```

So in your application, any time you move money out of the inventory (transfer `C`) you would also send transfers `A`+`B` in the same batch. If transfer `A` fails (e.g. [`error.exceeds_credits`](https://docs.tigerbeetle.com/reference/operations/create_transfers#exceeds_credits)), then you know that the inventory is empty, and your application can trigger whatever behavior it needs to. Likewise, if you are moving multiple values simultaneously in `C`, then `C` might fail even as `A`/`B` succeed (i.e. "there is a nonzero amount of inventory, but not enough to satisfy this particular request").

>  2) Is there a broadcast capability that one or multiple users can subscribe to a inventory items balance and get pushed new values as they change? E.g. a page may be subscribing to 100 or more balances and could be millions of users with any given combinations of products on screens showing real time balances (stock items remaining).

No broadcast capability; any pub/sub mechanics would need to be implemented outside of TigerBeetle.

If the inventory accounts set [`flags.history`](https://docs.tigerbeetle.com/reference/accounts/#flagshistory), then you can use [`get_account_balances`](https://docs.tigerbeetle.com/reference/operations/get_account_balances) as a change-data-capture stream (by polling it with successive timestamps). Then your application could distribute those updates to the users/connections monitoring the respective accounts.

(I think this would also work as an alternate solution to your first question.)

> Want to understand if capabilities exist, and if theres any limitation to scaling as in number of balances internally that can be monitored and max number of subscribes etc as well.. what would the first bottleneck be before we have to spin up a 2nd instance etc..

There is effectively no limit to the total number of balances (i.e. the number of accounts). That is, the only limit is the disk capacity. (And accounts are quite small.)
