### ISSUE TITLE
Panicked on Windows

### ISSUE THREAD

**Issue by azam** [tigerbeetle/tigerbeetle#1839]
Trying to run the prebuilt binaries panicked with the following message.

```
PS D:\data\tigerbeetle> .\tigerbeetle.exe format --cluster=0 --replica=0 --replica-count=1 0_0.tigerbeetle
Illegal instruction at address 0x7ff76276a6c5
Unable to dump stack trace: debug info stripped
```

Tried building per instruction on `README.md` but same result (instruction address is different).

```
PS D:\data\tigerbeetle> .\tigerbeetle.exe format --cluster=0 --replica=0 --replica-count=1 0_0.tigerbeetle
Illegal instruction at address 0x7ff6b982b695
Unable to dump stack trace: debug info stripped
PS D:\data\tigerbeetle>
```

Here is my environment:

OS: Windows 10 Pro
Build: 22H2 (19045)
CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz

**Comment by cb22** [comment]
Hey @azam! You're likely running in to https://github.com/tigerbeetle/tigerbeetle/issues/1592#issuecomment-1964865411.

Could you let us know if the workaround there (patching the build.zig file) works for you?

**Comment by azam** [comment]
@cb22 
Thank you, the patch works!
I hope there will be a mention on compiling for old CPU targets somewhere in the docs.
