### ISSUE TITLE
Tracking Issue: Reduce RSS for development environments

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#1884]
- https://github.com/tigerbeetle/tigerbeetle/pull/1882
- https://github.com/tigerbeetle/tigerbeetle/pull/1880
- https://github.com/tigerbeetle/tigerbeetle/pull/1883

**Comment by sentientwaffle** [comment]
- https://github.com/tigerbeetle/tigerbeetle/pull/1895
- https://github.com/tigerbeetle/tigerbeetle/pull/1897
- https://github.com/tigerbeetle/tigerbeetle/pull/1898

**Comment by sentientwaffle** [comment]
- https://github.com/tigerbeetle/tigerbeetle/pull/1981

**Comment by sentientwaffle** [comment]
- https://github.com/tigerbeetle/tigerbeetle/pull/2009

**Comment by sentientwaffle** [comment]
- https://github.com/tigerbeetle/tigerbeetle/pull/2010

**Comment by sentientwaffle** [comment]
- https://github.com/tigerbeetle/tigerbeetle/pull/2011

**Comment by sentientwaffle** [comment]
Closing this for now -- the RAM of a development replica is now down to ~660MiB (for a single-node cluster).

All of the above improvements will be part of the next release -- `v0.15.4`.

**Comment by matklad** [comment]
Awesome work @sentientwaffle ! You truly live up to the motto that "not only TigerBeetle is very fast, it is also small"!
