### ISSUE TITLE
Got thread panic: incorrect alignment error while performing load testing

### ISSUE THREAD

**Issue by MadanaGopalD** [tigerbeetle/tigerbeetle#1914]
I have created 6 replica to perform load testing and inserted 10Million accounts into it.
During creation process I stopped one instance(replica) and when I restarted it again I got an error which says:

![Screenshot from 2024-05-06 20-59-58](https://github.com/tigerbeetle/tigerbeetle/assets/107856105/d6a83120-cb3c-47d4-a5dd-ae2a0d5a9297)

What's causing this error?

**Comment by cb22** [comment]
Hi @MadanaGopalD!

Can you try again with our [debug build binary](https://github.com/tigerbeetle/tigerbeetle/releases/download/0.15.3/tigerbeetle-x86_64-linux-debug.zip) and post the stack trace? You should be able to extract it and run it on the same data file as-is.

**Comment by MadanaGopalD** [comment]
> Hi @MadanaGopalD!
> 
> Can you try again with our [debug build binary](https://github.com/tigerbeetle/tigerbeetle/releases/download/0.15.3/tigerbeetle-x86_64-linux-debug.zip) and post the stack trace? You should be able to extract it and run it on the same data file as-is.

Hi @cb22 
I have attached the stack trace.

/home/runner/work/tigerbeetle/tigerbeetle/src/message_bus.zig:712:47: 0x8971b2 in parse_message (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/src/message_bus.zig:698:48: 0x837911 in parse_messages (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/src/message_bus.zig:943:42: 0x7a1c9f in on_recv (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/src/io/linux.zig:808:29: 0x764130 in wrapper (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/src/io/linux.zig:545:28: 0x47c57f in call_callback (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/src/io/linux.zig:449:34: 0x43fea6 in complete (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/src/io/linux.zig:150:70: 0x43f173 in flush (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/src/io/linux.zig:110:27: 0x440b66 in run_for_ns (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/src/tigerbeetle/main.zig:288:38: 0x441731 in start (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/src/tigerbeetle/main.zig:72:44: 0x456114 in main (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/zig/lib/std/start.zig:574:37: 0x3ff16e in posixCallMainAndExit (tigerbeetle)
/home/runner/work/tigerbeetle/tigerbeetle/zig/lib/std/start.zig:243:5: 0x3fec51 in _start (tigerbeetle)
???:?:?: 0x3 in ??? (???)
Unwind information for `???:0x3` was not available, trace may be incomplete

![Screenshot from 2024-05-08 11-37-00](https://github.com/tigerbeetle/tigerbeetle/assets/107856105/3fd656dc-5d56-4670-a553-28f99ee49ece)

**Comment by MadanaGopalD** [comment]
@cb22 An update on the above issue will be helpful.

**Comment by cb22** [comment]
@MadanaGopalD thanks for the stack trace. It looks like it's [this issue](https://github.com/tigerbeetle/tigerbeetle/pull/1768) which landed the day after this last release.

We're gearing up to publish our next release (our weekly schedule has taken a bit of a break to get multiversion releases ready for a seamless upgrade process) but in the meantime, you should be able to continue your testing by building the latest TigerBeetle from source (`zig build install -Drelease -Dconfig=production`).

**Comment by matklad** [comment]
Fixed this a while ago!
