### ISSUE TITLE
incorrect alignment

### ISSUE THREAD

**Issue by s4ndeep4** [tigerbeetle/tigerbeetle#1915]
![Screenshot from 2024-05-07 14-33-40](https://github.com/tigerbeetle/tigerbeetle/assets/110333904/f9bd21a9-25fd-4a91-9b96-c8df21183c77)
Here I have created multiple data file and  1,2,3,4,5,6 and I have stopped 5 and  6 after stopping I have created accounts the data got inserted inside each file except that I have stopped  saying the error i have shared as a PNG file. why is this happened

**Comment by cb22** [comment]
Hey @sandeepanumula8690!

Can you try again with our [debug build binary](https://github.com/tigerbeetle/tigerbeetle/releases/download/0.15.3/tigerbeetle-x86_64-linux-debug.zip) and post the stack trace? You should be able to extract it and run it on the same data file as-is.
