### ISSUE TITLE
Tb is it ready for production?

### ISSUE THREAD

**Issue by Davidc2525** [tigerbeetle/tigerbeetle#1919]

**Comment by matklad** [comment]
In short, yes:

Longer version:

* we have one official production ready release
* it is our _first_ release, so there's still missing paint here and there
* production means that we provide specific guarantees, which are, at this point:
  * storage stability --- newer versions of TigerBeetle will be compatible with existing data files
  * safety --- (strict serializability & maintenance of double-entry account invariants)
 * notably, we are not quiet ready to guarantee full availability --- there are cases where cluster is unavailable even with fewer than `f` faults (which in our model include things like disk returning garbage data --- something which isn't even in scope for availability typically)

**Comment by kjloveless** [comment]
@matklad seems like this could be closed now :)

this is really more of a question (which has been answered), and not an issue.
do you think tigerbeetle could benefit from opening a discussions section?

i think these types of posts should be directed to a section like that.

thanks!

**Comment by matklad** [comment]
>do you think tigerbeetle could benefit from opening a discussions section?

We already have slack, which is indeed a better venue for such discussions, but we don't mind using issues for this.
