### ISSUE TITLE
docs: rename link Accounts -> Account

### ISSUE THREAD

**Issue by NikitaIT** [tigerbeetle/tigerbeetle#1930]
https://github.com/tigerbeetle/tigerbeetle/blob/aab8158f7c55658b415d12404b2aa0ed3d742935/src/clients/node/src/bindings.ts#L29

```diff
- See [history](https://docs.tigerbeetle.com/reference/accounts#flagshistory) 
+ See [history](https://docs.tigerbeetle.com/reference/account#flagshistory) 
```
https://docs.tigerbeetle.com/reference/account/#flagshistory

This file was auto-generated by node_bindings.zig.

**Comment by emschwartz** [comment]
Good catch, thanks for reporting this @NikitaIT!
