### ISSUE TITLE
zig build install -Drelease -Dconfig=production

### ISSUE THREAD

**Issue by s4ndeep4** [tigerbeetle/tigerbeetle#1954]
Hi @cb22, I have built the TigerBeetle from source (zig build install -Drelease -Dconfig=production) but it seems to be giving errors.
I have attached the details here

/home/sandeepka/Desktop/tigerbeetle-0.15.3/build.zig:1014:22: error: expected 2 arguments, found 3
        const self = @fieldParentPtr(FailStep, "step", step);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sandeepka/Desktop/tigerbeetle-0.15.3/build.zig:1039:22: error: expected 2 arguments, found 3
        const self = @fieldParentPtr(ShellcheckStep, "step", step);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sandeepka/Desktop/tigerbeetle-0.15.3/build.zig:1091:22: error: expected 2 arguments, found 3
        const self = @fieldParentPtr(GitCloneStep, "step", step);
![Screenshot from 2024-05-15 15-25-02](https://github.com/tigerbeetle/tigerbeetle/assets/110333904/f7e42ac6-7444-46a8-82c0-5a6f2905cb0d)

**Comment by sentientwaffle** [comment]
Hi @sandeepanumula8690,

TigerBeetle depends on Zig 0.11.0, not 0.12.0 ([yet](https://github.com/tigerbeetle/tigerbeetle/pull/1878)) -- they are not compatible.

**Comment by kjloveless** [comment]
@sentientwaffle Should this be closed?

required zig version can be [found here](https://github.com/tigerbeetle/tigerbeetle/blob/b983c1253697c3400757aefc71888e77e93fff97/build.zig#L45)

looks like it prints out a helpful error message and panics
