### ISSUE TITLE
Guidance Needed for Migrating Historical Transactions with Timestamps to TigerBeetle

### ISSUE THREAD

**Issue by breakds** [tigerbeetle/tigerbeetle#1968]
Hello,

We are currently in the process of migrating our accounting system to TigerBeetle and have encountered a challenge with preserving the original timestamps of our historical transactions. Our current system contains three years' worth of transaction data that we need to import into TigerBeetle.

## Issue:

Based on the documentation, we understand that TigerBeetle uses logical time for transactions, and timestamps cannot be updated after being set. This constraint poses a challenge for us as we need to maintain the integrity and sequence of our historical transactions.

## Specific Questions:

1. What is the recommended approach for migrating historical transactions with their original timestamps to TigerBeetle, considering the logical time constraints?
2. Are there any best practices or tools within TigerBeetle that can assist with this type of data migration?
3. A slightly 

## Related Question:

If the TigerBeetle servers go down (e.g., due to a power failure) and it takes 2 hours to restore, will transactions that occur during that downtime, once backfilled, be timestamped 2 hours later than they actually occurred? This discrepancy could affect hourly balance reports. What is the recommended approach to handle this scenario to ensure accurate reporting?

Any guidance or recommendations you can provide would be greatly appreciated. Thank you for your support!

**Comment by matklad** [comment]
Thanks for reaching out @breakds!

This particular area is a work-in-progress, so sadly there's no a ready-made solution yet (or rather, we have some code in place to do this, but it isn't a production-ready feature yet).

The overall shape of the solution is likely going to be a separate request or a flag to allow the timestamps to be filed by user for some initial portion of cluster's livetime.

So I actually have two questions here:

* do you have a guarantee that all your existing timestamps are unique? 
* during migration, can you guarantee that all transfers will be submitted in order of increasing timestamps?

If the answer to both questions is yes, then I think we should be able to injest these data

As for the related question:

From the perspective of TigerBeetle's data model, there's only a single transaction timestamp --- that when the transaction was processed by the cluster. This timestamp is assigned by the cluster. So, in the described scenario, all txes will be timestamped with the later time, when they are executed.

You can however use one of the user_data fields to record time-of-submission for transactions. Though, for reporting purposes you probably want to use execution time (or our exisint historical account balances feature), as that's the timestamp where the effect of TX actually takes place.

**Comment by batiati** [comment]
To complement matklad’s answer, we also started discussing the design of a similar feature in the issue below; please take a look and give your feedback!

https://github.com/tigerbeetle/tigerbeetle/issues/1893

**Comment by breakds** [comment]
@matklad @batiati Thanks a lot for the prompt reply!

> The overall shape of the solution is likely going to be a separate request or a flag to allow the timestamps to be filed by user for some initial portion of cluster's livetime.

That sounds good!

> do you have a guarantee that all your existing timestamps are unique?
> during migration, can you guarantee that all transfers will be submitted in order of increasing timestamps?

I think we can answer "yes" to both of the questions.

> Though, for reporting purposes you probably want to use execution time (or our existing historical account balances feature), as that's the timestamp where the effect of TX actually takes place.

I see! We are actually not using `TigerBeetle` as the sole source of truth. In fact, we are using it to keep track of all our transactions at a few other exchanges and keep them all in one place. Does this sound like unintended use case of TigerBeetle?

Thanks a lot!

**Comment by batiati** [comment]
Closed by https://github.com/tigerbeetle/tigerbeetle/pull/2171
