### ISSUE TITLE
question - re: splitting out IO package

### ISSUE THREAD

**Issue by zachgrayio** [tigerbeetle/tigerbeetle#1988]
hey folks! I've been lurking on this project for quite some time, really cool stuff here

I was wondering if any progress is being made towards the idea of releasing the tigerbeetle IO package as a standalone lib that we can use in other projects easily via an exposed C API, as alluded to here https://tigerbeetle.com/blog/a-friendly-abstraction-over-iouring-and-kqueue

I'd love to see this happen, is this something the community can contribute?

**Comment by matklad** [comment]
This more or less exists here: https://codeberg.org/dude_the_builder/iofthetiger

We (TigerBeetle devs) are unlikely to directly package any of our code as reusable libraries, as we are pretty narrowly focused on our specific needs, but we are _very_ encouraging of the community just forking the code and running with it, which have been happening with some libraries of our own already.

**Comment by matklad** [comment]
And you might also want to take a look at https://github.com/mitchellh/libxev

**Comment by zachgrayio** [comment]
awesome thanks! this is great
