### ISSUE TITLE
Consider adding a .zigversion file?

### ISSUE THREAD

**Issue by photex** [tigerbeetle/tigerbeetle#1998]
Hello tigerbeetle devs!

In order to test and validate my Zig launcher: https://github.com/photex/ziege/ I have been building various projects using it.

Users of ziege (... which might only be myself at this point :sweat_smile:) can use `zig +version=0.11.0 build` to build this project, but with the .zigversion it would be as simple as `zig build`.

Cheers!

**Comment by matklad** [comment]
Thanks for the suggestion, but I think we'll not do this at the moment!

One of the principles of TigerBeetle is that we minimize dependencies (on 3rd party tools, on library APIs, on OS syscall interface, etc). So, until some sort of version manager becomes an official part of Zig's toolchain, we'd rather stick to what we have today:

```console
./scripts/install_zig.sh
./zig/zig build
```
