### ISSUE TITLE
Bug: Huge SuperBlock zone read

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#200]
Via Discord:

> When using a 5 replica system, the tests will bring down one of the replicas with something similar to:

```
2022-10-13 20:03:09 Jepsen starting  /root/tigerbeetle/tigerbeetle start --addresses=192.168.122.101:3000,192.168.122.102:3000,192.168.122.103:3000,192.168.122.104:3000,192.168.122.105:3000 /root/tigerbeetle/data/0_3.tigerbeetle
info(io): opening "0_3.tigerbeetle"...
info(main): 3: cluster=0: listening on 192.168.122.104:3000
info(message_bus): connected to replica 4
info(message_bus): connection from replica 0
info(message_bus): connection from replica 1
info(message_bus): connection from replica 2
...
error(storage): short read: buffer.len=699678720 offset=65536 bytes_read=0
thread 1176 panic: data file inode size was truncated or corrupted
```

> The > the # of replicas, the quicker the panic shows.
> And with debug true in this test, the panic doesn't express.

---

- I'm not sure where this read originates is yet — we shouldn't ever be reading a buffer that large.
- That offset is within the SuperBlock zone, `copy=0`, within the trailers. Because trailers are encoded as variable-length it is hard to say which that is.

**Comment by nurturenature** [comment]
Hi,

Confirming that the repository >= [SuperBlock: Fix client table body decoding](https://github.com/tigerbeetledb/tigerbeetle/commit/738108f908f0649f0565ac1986bff834efecb78d) exhibits no errors/panics, while the repository < this version is problematic using the Java client.

Thanks for the feedback on Discord.
I've updated the tests to include `--tigerbeetle-update git-revision`, `--tigerbeetle-log-level #`, and `--tigerbeetle-debug? boolean` for better issue reporting going forward.

And as I hope to be more signal than noise, apologies for raising an issue in the past.

**Comment by sentientwaffle** [comment]
Nothing to apologize for! Thanks for confirming this too.
