### ISSUE TITLE
Build failure when building locally using zig installed using homebrew

### ISSUE THREAD

**Issue by Bandisa** [tigerbeetle/tigerbeetle#2007]
Good day

## Summary

I just tried to build tigerbeetle locally using zig but it immediately fails with a somewhat undescriptive error. 

## What I have done so far

I installed zig on my machine using `homebrew`. It builds successfully if I use the  `scripts/install_zig.sh` script to install it but the error does not really explain why I can't or should not build it using the homebrew install. 

I have installed `shellcheck` and `git` so I am not sure why the build is failing at those checkpoints.

## Question
Any idea why this is happening?

## Change Request
Could you please cover it in your installation guide too because though it makes sense to install project dependencies on the actual project using git submodules as you have been, I would like to use `homebrew` to manage all of my main packages for something big like zig -> I'm using a 256GB MBA 🫠.

## Extra
I tried looking at the build script but it is unclear what the error is. 

PS: I am new to zig.

<img width="1470" alt="image" src="https://github.com/tigerbeetle/tigerbeetle/assets/89698022/047f1bc8-e843-4367-a80f-11494e0a8553">

<img width="1252" alt="image" src="https://github.com/tigerbeetle/tigerbeetle/assets/89698022/7f0a411f-e49a-4b29-902a-2eba5e196ad3">

**Comment by matklad** [comment]
>I installed zig on my machine using homebrew

As per our build instructions, the only supported way to build TigerBeetle is by using `install_zig` script to install the right version of Zig:

```
git clone https://github.com/tigerbeetle/tigerbeetle.git
cd tigerbeetle
./scripts/install_zig.sh # There's a .bat version for Windows.
./zig/zig build -Drelease
./tigerbeetle --version
```

https://github.com/tigerbeetle/tigerbeetle/blob/main/docs/HACKING.md#building

We don't officially support building with distribution-provided Zig. It will almost certainly work, but then it's on you to make sure you are using the correct version. At the time of writing, you need Zig 0.11.0 and it looks like you are using 0.12 or 0.13 instead.

**Comment by Bandisa** [comment]
Could you please at least list the supported zig version on the README or on any of the docks? This comment on the installation script implies that you support an explicit release version of zig and no where in the docs I have read does it mention the zig version explicitly (could be wrong).

https://github.com/tigerbeetle/tigerbeetle/blob/3c9cc16d75cc821f97ebfad12e1404cc6f1e801c/scripts/install_zig.sh#L5

Yes you are correct on the version, I ran the script and passed in a higher version and it failed.

Thank you for your assistance.

<img width="1116" alt="image" src="https://github.com/tigerbeetle/tigerbeetle/assets/89698022/28fb7728-8087-48a4-ad84-13a221de0c9a">

**Comment by matklad** [comment]
I think I'd rather not --- the version of Zig we use is a private implementation detail. Who knows, maybe one day we'll switch to Rust :) 

The thing is, using an unstable language is hard --- you need to hold it just the right way to make it work. It is much easier for us to maintain a single `install_zig` script we write in a very rigid way, then to try to support unbounded number of ways a Zig compiler could be installed. 

As an example of problem this could create, some distro-packaged versions of Zig might (rightfully) build it with a distro-packaged version of LLVM, which _might_ cause miscompilations for TigerBeetle. To avoid thinking about this sorts of problems our policy is:

* `./scripts/install_zig.sh && ./zig/zig build` is the only supported and documented way to build TigerBeetle
* you can of course read what `install_zig.sh` is doing and use a "matching" version of Zig you obtained in some other way, but then it's on you to debug any issues that might arise from that

When Zig releases a stable version we might revise that policy, as, at that point, there would be a much more clear contract about what Zig is, but at this point we'd rather stay very focused on our very specific needs.

**Comment by Bandisa** [comment]
I understood your initial response regarding the version and I am not asking you to support multiple ways to install zig, I am just pointing out that the comment implies something beyond your intent and this detail about the main dependency of the project is important as we have seen with this error. 

Documentation and comments should reflect the true intent to avoid unnecessary error like this - in this case, you support an explicit version of a language that is the main dependency. Just one line on your docs/readme or removing the `an explicit release version`  wouldn't hurt right?
You know for a fact that zig 0.11.0 is what is supported, think it's best everyone knows instead of just pointing to an installation script.

Then again, this is a tangent I guess. Thank you very much.
