### ISSUE TITLE
What about regular data?

### ISSUE THREAD

**Issue by sirinath** [tigerbeetle/tigerbeetle#202]
I would like the same speed and guarantees from a regular DB.

Can you guys release multiple DBs. One for accounts, one for time series data and one for regular data. Or add the ability to support this in the existing DB itself.

Also sometimes financial data like stock prices or quotes fits better in a time series oriented DB.

**Comment by jorangreef** [comment]
Thanks @sirinath ! Appreciate your confidence in TigerBeetle.

We have heard from other people about this too, since TigerBeetle's fault models are stricter.

Long term, we are designing TigerBeetle as a library that will support custom state machines, i.e. custom business logic.

**Comment by sirinath** [comment]
@jorangreef Hopefully we will see this soon. A generic TigerBeetleDB for all data (accounting, time series, structured, semi and unstructured, dimensional, tensor, sparital, etc.)

**Comment by jorangreef** [comment]
Thanks @sirinath that will be something! I hope that as a library we may well see this.
