### ISSUE TITLE
latency spike/cycle every ~128 operations, correlates with: replica: on_request: ignoring op=... (too far ahead, checkpoint=...)

### ISSUE THREAD

**Issue by nurturenature** [tigerbeetle/tigerbeetle#205]
Hi,

Increasing the timeout for client operations to several seconds will allow the operation to complete in a multi replica/client config.
It does show an interesting pattern with latency.

For a baseline view, 1 replica and 1 client.
(If you squint a bit, can you see a wave pattern in the latency times?)

![1r-1c](https://user-images.githubusercontent.com/86082495/196059026-d2981f3e-4b06-4261-93ba-1c5cee25a3d3.png)

----

Going to 1 replica with 3 clients gives a clearer picture.
There's a (us -> ms -> s -> spike/pause... -> repeat) cycle in latency times.

![1r-3c](https://user-images.githubusercontent.com/86082495/196059084-842d049c-c5e7-4ab6-8437-1593d91398b0.png)

----

It gets more pronounced with more replicas/clients.
E.g. max latency increases to > 10s with 5 replicas, 16 clients.

Patterns observed:

  - latency spikes/cycles occur ~128 operations regardless of replica/client count, rate of operations
    - operations are a random mix of lookupAccounts(batch[8]) or createTransfers(batch[1]) 
  - ave/max latency, pause, are higher and increase faster with higher number of replicas/clients
  - throughput is limited by increasing latency, pause
  - database remains consistent across all clients, operations

In looking at the logs, there a correlation, # of unique "ignoring op, too far ahead" == # latency cycles:

```
grep "ignoring op\=.*too far ahead" n1/tigerbeetle.log | uniq --count 

3 debug(replica): 0: on_request: ignoring op=128 (too far ahead, checkpoint=0)
3 debug(replica): 0: on_request: ignoring op=252 (too far ahead, checkpoint=123)
3 debug(replica): 0: on_request: ignoring op=376 (too far ahead, checkpoint=247)
3 debug(replica): 0: on_request: ignoring op=500 (too far ahead, checkpoint=371)
3 debug(replica): 0: on_request: ignoring op=624 (too far ahead, checkpoint=495)
3 debug(replica): 0: on_request: ignoring op=748 (too far ahead, checkpoint=619)
3 debug(replica): 0: on_request: ignoring op=872 (too far ahead, checkpoint=743)

# note: duplicate log message count == client count 
```
----

Tested with git b68add563984bfab4268e25129c8f7604fd5651c
main at time of submission

**Comment by sentientwaffle** [comment]
Good catch, @nurturenature! This is actually a known issue :smile:. Every wrap of the WAL (128-4 operations in a debug build) we need to "checkpoint" before we are able to "wrap" the WAL and start overwriting old entries. Part of the checkpoint process involves saving some state for each client (hence the correlation you found). We already have a plan to address this (as part of a larger change to efficiently support a higher client count).

The `too far ahead` is a separate thing — it is part of a workaround until we build the ability for a replica that falls behind to "catch up" more than 1 WAL.

Thanks for the great write-up!

**Comment by nurturenature** [comment]
Thanks for the explanation and being good natured about reporting a known. 
I get excited when there's binary count cycles and log correlation. 🙂

So at the current time, a good multi r, multi c config to develop and test with would be: 3 replicas, 5 clients, ~10+ tps.
Applying more transactional pressure after that will only slow things down

![3r-5c](https://user-images.githubusercontent.com/86082495/196062161-3f401694-9e19-40b4-8193-43e113e74ecb.png)

Also known WAL checkpoints could be a good opportunity to fuzz around and in. 🤔

As it's known, will close to keep Issues current.
