### ISSUE TITLE
Build tigerbeetle bin in test_min configuration in CI

### ISSUE THREAD

**Issue by brson** [tigerbeetle/tigerbeetle#2051]
https://github.com/tigerbeetle/tigerbeetle/pull/2036 fixed the test_min build, but it shouldn't have broken in the first place. Add CI to build the main tigerbeetle bin in this configuration.

I am not sure offhand the correct way to add this to CI - whether it should be part of the main test suite or CI-only, etc.

**Comment by matklad** [comment]
Will fold this into https://github.com/tigerbeetle/tigerbeetle/pull/2047.

I am also a bit uneasy with our configuration matrix --- we have _so many_ ways to configure TigerBeetle! I wonder if we can reduce dimensionality here somehow...

**Comment by matklad** [comment]
Done!
