### ISSUE TITLE
add 'last_transfer_id' to accounts

### ISSUE THREAD

**Issue by hookla** [tigerbeetle/tigerbeetle#2105]
add a reference to the last transfer that effected a balance change on the account

**Comment by batiati** [comment]
Hello @hookla! Materializing the "last update event" is indeed something that we have considered in the past, but we decided to solve this in the read path instead.

Using `get_account_transfers` with `limit=1` and `flags=reversed`, you can retrieve the last transfer that affected the balance. The same applies to `get_account_balances` if the account has the `history` flag set.
Here's an example using the TigerBeetle REPL (but you can do the same in any language client):
```
./tigerbeetle repl --cluster=0 --addresses=3000 \
    --command="get_account_transfers account_id=X limit=1 flags=debits|credits|reversed;"
```
