### ISSUE TITLE
Zig client?

### ISSUE THREAD

**Issue by bruvduroiu** [tigerbeetle/tigerbeetle#2110]
Hi TB team,

Apologies if this question is obvious.

I want to write a Zig application that makes use of Tigerbeetle, and while there are plenty of clients for Go/C/..., I couldn't find a way to get a Zig client going.

Theoretically, the C client could be used via Zig C-interop, but that seems quite awkward no?

What's the best way to interact with TB from a Zig application?

**Comment by matklad** [comment]
Hi @bruvduroiu! Right now, we don't officially support Zig --- as the language it still unstable, we are treating Zig as our internal implementation detail, and don't expose anything Zig specific in our public interfaces. 

That being said, we have a low-level Zig client in this repository:

https://github.com/tigerbeetle/tigerbeetle/blob/d3a4aafb9e630a25ac8acafbdedfaa7a380cbe64/src/vsr/client.zig

No good docs at the moment, but you might want to take a look at how we use it from our benchmark load script:

https://github.com/tigerbeetle/tigerbeetle/blob/d3a4aafb9e630a25ac8acafbdedfaa7a380cbe64/src/tigerbeetle/benchmark_load.zig#L77-L87

**Comment by bruvduroiu** [comment]
Many thanks for pointing me in the right direction! Will try to hack something together

**Comment by ashtyn3** [comment]
I'm commenting on this issue again to share a client implementation I've made. It is in feature parity with the rest of the clients.
[client source code](https://github.com/ashtyn3/tigerbeetle-zig-client)
