### ISSUE TITLE
Inconsistent reporting of account balance by lookup_accounts for expired pending transfers 

### ISSUE THREAD

**Issue by ikolomiets** [tigerbeetle/tigerbeetle#2118]
I stumbled upon what seems to me as a bug. I verified it with latest master build.

So far my intuition about pending transfers in TBDB was that when such transfer expires, the subsequent call to `lookup_accounts` will return updated (voided) pending balances, but this is not the observed behaviour.

Here's a demonstrator code:

```java
public class ReserveFunds {

    private static final Client client = new Client(UInt128.asBytes(0), new String[]{"10.8.0.1:3000"});

    public static void main(String[] args) throws InterruptedException {
        int ledgerId = 61;
        UUID debitAccountId = UUID.fromString("be3999e7-70ed-430c-ab38-b8527ecdf52d");
        UUID creditAccountId = UUID.fromString("07c9ff85-2ca8-489c-8053-02ab2c09b0f1");

        System.out.println("Balance before: " + getAccountBalance(debitAccountId)); // initial balance is 10
        reserve(UUID.randomUUID(), ledgerId, debitAccountId, creditAccountId, 10, 5); // debit 10, expires in 5 seconds
        Thread.sleep(10 * 1000); // wait 10 seconds
        System.out.println("Balance after: " + getAccountBalance(debitAccountId)); // 5 seconds after expiry, the balance is still 0
    }

    public static void reserve(UUID reserveTransferId,
                               int ledgerId,
                               UUID debitAccountId,
                               UUID creditAccountId,
                               long amount,
                               int timeout) {
        TransferBatch transferBatch = new TransferBatch(1);
        transferBatch.add();
        transferBatch.setId(UInt128.asBytes(reserveTransferId));
        transferBatch.setFlags(TransferFlags.PENDING);
        transferBatch.setLedger(ledgerId);
        transferBatch.setCode(3); // code=3 is for reserve
        transferBatch.setDebitAccountId(UInt128.asBytes(debitAccountId));
        transferBatch.setCreditAccountId(UInt128.asBytes(creditAccountId));
        transferBatch.setAmount(amount);
        transferBatch.setTimeout(timeout);

        try {
            CreateTransferResultBatch resultBatch = client.createTransfers(transferBatch);
            if (resultBatch.next()) {
                throw new RuntimeException("CreateTransferResult=" + resultBatch.getResult());
            }
        } catch (ConcurrencyExceededException e) {
            throw new RuntimeException(e);
        }
    }

    public static long getAccountBalance(UUID accountId) {
        try {
            IdBatch idBatch = new IdBatch(UInt128.asBytes(accountId));
            AccountBatch accountBatch = client.lookupAccounts(idBatch);
            if (!accountBatch.next()) {
                throw new RuntimeException("Account Not Found");
            }

            long credits = accountBatch.getCreditsPosted(UInt128.LeastSignificant) +
                    accountBatch.getCreditsPending(UInt128.LeastSignificant);
            long debits = accountBatch.getDebitsPosted(UInt128.LeastSignificant) +
                    accountBatch.getDebitsPending(UInt128.LeastSignificant);

            return credits - debits;
        } catch (ConcurrencyExceededException e) {
            throw new RuntimeException(e);
        }
    }

}
```

I would expect to get balance=10 after the sleep (5 seconds since the transfer expired), but I still get balance=0.
But, when I re-run this code immediately after, then the first getAccountBalance properly returns balance=10, as I would expect.

What is more interesting - while the original process sleeps in the `Thread.sleep(10 * 1000)`, should there be another client connection (in different process) that requests `lookup_accounts` (not necessarily for accounts involved in the ongoing pending transfer) then once `Thread.sleep(10 * 1000)` is done the `getAccountBalance(debitAccountId)` reports proper balance=10.

What is going on here?

**Comment by batiati** [comment]
Thanks for reporting this @ikolomiets! I could reproduce it with unit tests, and I'll dig a bit more to understand the problem.

**Comment by ikolomiets** [comment]
That was fast! I confirm - the `batiati-fix-timeout` branch fixes this issue. I'm very glad my report helped to squash another bug. But this begs the question - why the advanced fuzzing and DST couldn't find such bug earlier? Or put in another way - are there kinds of bugs that are harder to catch by fuzzing?

**Comment by batiati** [comment]
> why the advanced fuzzing and DST couldn't find such bug earlier?

It's an excellent question! This bug caught my attention for the same reason, and the answer is very mundane: It only happens when the cluster is idle, as soon an operation arrives, the timestamp flag would correctly trigger the pending balance timeout (as you noticed, even if another client submitted an operation unrelated to the account in question). So, the status-quo implementation of our simulator would ~never~ hardly catch this, just because the cluster is never idle during the simulation (except for the liveness check at the very end, when we intentionally leave the cluster idle and wait for it to repair itself.

This PR was only a small part of it, now we need to evolve the simulator to properly explore this space of things we expect to happen automatically (e.g expiration and upgrades) even -- but not necessarily -- when the cluster is idle!

And again, thank you so much for reporting it with such precision and detail! 🎉

**Comment by ikolomiets** [comment]
Good to know. Indeed, this case (and similar) when treated properly (as you do plan) should further increase the value of DST by targeting newly found failure space.
