### ISSUE TITLE
random transactions (w/no environmental faults) can panic or cause the replica to become unavailable

### ISSUE THREAD

**Issue by nurturenature** [tigerbeetle/tigerbeetle#215]
`jepsen-tigerbeetle` is fuzzing its way into panics and an unavailability doing random transactions in a no fault environment.

These are grouped together in a single issue as they represent the current known failed outcomes.

And hopefully as a way to learn how to get this class of coverage into VOPR.

With 1 replica, 1 client, ~4-5k transactions:

----

```
/root/tigerbeetle/src/lsm/table_iterator.zig:270:23: 0x2b9667 in lsm.table_iterator.TableIteratorType(lsm.table.TableType(u128,lsm.groove.IdTreeValue,lsm.groove.IdTreeValue.compare_keys,lsm.groove.IdTreeValue.key_from_value,554112867134706473364364839029663282043,lsm.groove.IdTreeValue.tombstone,lsm.groove.IdTreeValue.tombstone_from_key),storage.Storage).peek (tigerbeetle)
                assert(it.data_block_index == Table.index_data_blocks_used(it.index_block));
```

[it.data_block_index-tail-500.log](https://github.com/tigerbeetledb/tigerbeetle/files/9841785/it.data_block_index-tail-500.log)

----

A resurrection? of #183:  

```
/root/tigerbeetle/src/lsm/compaction.zig:450:19: 0x48b380 in lsm.compaction.CompactionType(lsm.table.TableType(u128,lsm.groove.IdTreeValue,lsm.groove.IdTreeValue.compare_keys,lsm.groove.IdTreeValue.key_from_value,554112867134706473364364839029663282043,lsm.groove.IdTreeValue.tombstone,lsm.
groove.IdTreeValue.tombstone_from_key),storage.Storage,lsm.table_immutable.TableImmutableIteratorType).cpu_merge_start (tigerbeetle)
            assert(!compaction.data.writable);
```
[compaction.data.writable-tail-500.log](https://github.com/tigerbeetledb/tigerbeetle/files/9841596/compaction.data.writable-tail-500.log)

----

Replica can become indefinitely unresponsive, log messages loop:
 
```
debug(vsr): 0: repair_timeout fired
debug(vsr): 0: repair_timeout reset
debug(vsr): 0: ping_timeout fired
debug(vsr): 0: ping_timeout reset
debug(vsr): 0: commit_timeout fired
debug(vsr): 0: commit_timeout reset
debug(vsr): 0: repair_timeout fired
debug(vsr): 0: repair_timeout reset
debug(vsr): 0: repair_timeout fired
debug(vsr): 0: repair_timeout reset
```

**Comment by sentientwaffle** [comment]
Thanks, @nurturenature, this is great! Which commit are you running?

**Comment by nurturenature** [comment]
642e2e905e1a1827e7b08dcca602888c9962db88 which includes all of the latest LSM commits.

**Comment by sentientwaffle** [comment]
Perfect; thank you! I'll check it out.

**Comment by sentientwaffle** [comment]
Can you double-check the commit number your replicas are running? From [it.data_block_index-tail-500.log](https://github.com/tigerbeetledb/tigerbeetle/files/9841785/it.data_block_index-tail-500.log):

```
/root/tigerbeetle/zig/lib/std/debug.zig:225:14: 0x269bcb in std.debug.assert (tigerbeetle)
    if (!ok) unreachable; // assertion failure
             ^
/root/tigerbeetle/src/lsm/table_iterator.zig:270:23: 0x2b9667 in lsm.table_iterator.TableIteratorType(lsm.table.TableType(u128,lsm.groove.IdTreeValue,lsm.groove.IdTreeValue.compare_keys,lsm.groove.IdTreeValue.key_from_value,554112867134706473364364839029663282043,lsm.groove.IdTreeValue.tombstone,lsm.groove.IdTreeValue.tombstone_from_key),storage.Storage).peek (tigerbeetle)
                assert(it.data_block_index == Table.index_data_blocks_used(it.index_block));
                      ^
/root/tigerbeetle/src/lsm/level_iterator.zig:296:36: 0x2b92c0 in lsm.level_iterator.LevelIteratorType(lsm.table.TableType(u128,lsm.groove.IdTreeValue,lsm.groove.IdTreeValue.compare_keys,lsm.groove.IdTreeValue.key_from_value,554112867134706473364364839029663282043,lsm.groove.IdTreeValue.tombstone,lsm.groove.IdTreeValue.tombstone_from_key),storage.Storage).pop (tigerbeetle)
            if (table_iterator.peek() == null) it.tables.advance_head();
                                   ^
```

But as of https://github.com/tigerbeetledb/tigerbeetle/pull/177 `table_iterator.peek()`'s type signature is `fn peek(it: TableIterator) error{Empty, Drained}!Table.Key` (previously it was `fn peek(it: TableIterator) ?Table.Key`).

**Comment by nurturenature** [comment]
> Can you double-check the commit number your replicas are running?

And dang it, 😔, the scripts weren't git switching appropriately so you are correct, these panics/behaviors were from before the latest LSM work.

And with the appropriate commits, ran the tests overnight for 8 hours of 15 minute tests through different replica/client/worker configs:

```
0 unknown
0 crashed
0 failures
```
And *no* client evictions were triggered either!  🙏

May be at the point where an app can run a cluster indefinitely in a no fault environment. Will do some long running tests over the next several days.

And once again, apologies for finding yesterday's bugs and surfacing them as current.

I will do better with the upcoming partition panics.

Closing, all issues raised confirmed fixed.

**Comment by sentientwaffle** [comment]
No worries! I too am familiar with the confusing disappointment of not finding bugs in code. :wink: 

Just so you know, partition panics around `op_checkpoint` assertions will usually be because we haven't implemented state transfer yet. There is a stopgap "fix" (aka kludge) in https://github.com/tigerbeetledb/tigerbeetle/pull/141: https://github.com/tigerbeetledb/tigerbeetle/blob/f68358a708636c0f0c82dc3859e07fe7a16ae216/src/vsr/replica.zig#L973 to try to keep the cluster from progressing until all replicas have reached a checkpoint, but it isn't foolproof (it can be circumvented with carefully-timed crashes in the proximity of checkpoints). And of course, this workaround makes checkpoint latency even worse :grin:.

Re: disk faults, until grid recovery is implemented, we can only handle them in the WAL zone and, to a lesser degree, the superblock zone (I have a fix for that in the works).
