### ISSUE TITLE
Support for U256 balances and transfers

### ISSUE THREAD

**Issue by NduatiK** [tigerbeetle/tigerbeetle#2166]
I have been looking into TigerBeetle as a transaction processing database for blockchain token transfers. TigerBeetle looks processing, however, token amounts are typically U256 numbers on most ethereum networks. Is there an easy way to change the data type for transcation amounts and balances to U256 numbers.

I saw @eatonphil had [mentioned some discussions](https://news.ycombinator.com/item?id=36681335#36686627) with blockchain companies and was hoping you would have some suggestions.

Thanks!

**Comment by matklad** [comment]
No, there's no easy way to change this. Our balances are `u128`. It _is_ possible to build a custom version of TigerBeetle which uses `u256` for balances, but that would be a medium-sized change on the database-side, and a large-ish change on the clients side, and is not something we are directly interested in maintaining at this point.

So, right now the only way to make this work is by _mapping_ u256 amounts to u128. For example, if all u256 are actually small, you can store them in u128. TigerBeetle correctly handles overflows, so, if at some point some balance overflows at TigerBetele side, no funds will be lost.

Another alternative is to use asset scale. You can say that amount of X in TigerBeetle represents X*(1<<128) original tokens and require that all TigerBeetle tracked transfers are a multiple of that.

**Comment by NduatiK** [comment]
Thanks @matklad, I'm glad to hear that overflows are handled, we'll stick to u128 and manually handle detected overflows in our application logic.
