### ISSUE TITLE
Question: How would you handle deposits and withdrawals scenarios

### ISSUE THREAD

**Issue by JohnKinyanjui** [tigerbeetle/tigerbeetle#2194]
Hello, just started working with tigerbettle in my current Job [creating a wallet based system], so am not good with accounting systems but been trying to get a hang of it,

So to my question i wanted to understand the most optimal way to either deposit or withdrawal money from an account noting this transfer has no co-relation to any account. So my solution was to create an account which will act as the "Treasury" and users can use it in the scenarios i mentioned. But now adding the unlimited debits and credits units thought it could cause perfomance issues dure to the large number of calculations.

I would really love your suggestions or how i can better do this.

**Comment by matklad** [comment]
Yes, a Treasury account is a good way to model this! I'd generally won't worry about performance here -- TigerBeetle is hyper optimized exactly for the case where you have few hot accounts, so this all should run very very fast!

**Comment by JohnKinyanjui** [comment]
thanks for response, i will continue with this approach
