### ISSUE TITLE
Memory Fault Model and ECC memory schemes

### ISSUE THREAD

**Issue by Cfouria** [tigerbeetle/tigerbeetle#233]
Hello, I was reading the Design doc of this awesome project, saw the ECC mention, and found: 
>"all DDR5 chips have on-die ECC... This, however, is not the same as true ECC memory... have extra data lines to the CPU to send error-detection data, letting the CPU detect and correct errors that occurred in transit."

Confused I searched and found Side-band ECC, On-die ECC, Inline ECC(LPDDR only?), and Link-ECC(LPDDR only?) schemes. Edit: [MemTest86 seems good source](https://www.memtest86.com/ecc.htm)
I thought that 'DDR5 has ECC' before this and imagine others will too.

So, will On-die ECC will be good enough?
Or, is On-die ECC only going to be a 'Non-ECC memory is not supported by TigerBeetle?'

**Comment by jorangreef** [comment]
Thanks @Cfouria for raising a great question—the difference between what seems to be hop-by-hop (on-die ECC) vs end-to-end correction (CPU error-detection).

TigerBeetle does not detect the type of memory used, so perhaps we could change "not supported by" to read "not targeted by" or "not recommended", leaving the difference between on-die vs CPU error detection to the operator, according to their risk profile.

**Comment by sentientwaffle** [comment]
Updated in https://github.com/tigerbeetledb/tigerbeetle/pull/222/commits/6e7336d4c1743aad017dfbfc2838dde4ff7e6ea6

**Comment by Cfouria** [comment]
I agree it's the operators choice. Just worried about how on-die is being advertised as ECC. And that worry isn't the responsibility of this project. Thanks for your time!
