### ISSUE TITLE
Guidance Needed: Modeling Loan Accounts and Transactions in a Lending System Using TigerBeetle

### ISSUE THREAD

**Issue by Bayonle** [tigerbeetle/tigerbeetle#2331]
I'm building a core banking system for loans and deposits, and I'm considering using TigerBeetle to handle the financial accounting aspects of the system. In my scenario:

**Loan Accounts:** Each customer loan has distinct principal, interest, penalty and fees balances. Should I model these components using separate TigerBeetle accounts for each (e.g., a principal account, an interest account, and a fee account), or is there a more efficient way to handle these distinctions using a single TigerBeetle account with different transaction codes? It would also be required to be able to display a list of customers' loan accounts and be able to specify the principal, interest, fees, penalty balances and what portion of those have been paid. The other alternative I've thought of is to keep those components as metadata in my database but that would require doing separate calculations to recognise those components while only using a single tigerbeetle account to store the total loan balance.

**Accounting Entries:** Loan disbursements generate accounting entries that affect multiple accounts (e.g., debiting a portfolio control account and crediting the transaction source and fee accounts). What would be the best way to model this in TigerBeetle, given that loan accounts are not general ledger accounts, but are tracked for individual customers?

**Fetching all loan balances:** If a tigerbeetle account represents individual loan accounts, what would be the best approach to fetch all loan accounts from tigerbeetle considering the available methods are just to look up one or more accounts by their Id? Would that require keeping the loan accounts in my external database and using the tigerbeetle id to do a batch lookup and then merging the results?

Any guidance or suggestions on best practices for modelling this type of use case would be greatly appreciated!

**Comment by matklad** [comment]
Hello @Bayonle 

**Loan Accounts** --- the best is probably to use separate TigerBeetle account for each balance. This _is_ efficient. 

**Accounting Entries:**

>Loan disbursements generate accounting entries that affect multiple accounts

Yes, this is _precisely_ the use-case we designed TigerBeetle for! In TigerBeetle, you can link several transfers together, to make sure they happen (or not happen) atomically:

https://docs.tigerbeetle.com/coding/recipes/multi-debit-credit-transfers

**Fetching all loan balances:** there are two options to do this:

* You can store mapping between internal TigerBeetle accounts and the logical loan accounts in an external database, and then use lookup_accounts with specific list of ids: https://docs.tigerbeetle.com/coding/system-architecture
* Alternatively, you can use `user_data` field on the account to specify the ID of logical loan account. Then, you should be able to query all accounts with matching user_data: https://docs.tigerbeetle.com/reference/account-filter#user_data_128

**Comment by Bayonle** [comment]
Thank you for your guidance. 
_Account fields cannot be changed by the user after creation. However, debits and credits fields are updated by TigerBeetle as transfers move money to and from an account._

The above is from the documentation on Accounts and I have a few questions. Imagine a savings/account that's created with a debit_must_not_exceed_credit flag which prevents the account from going into negative. So this runs for a while and then we decided to start allowing overdrafts. This means that the existing flag would prevent overdrafts. The credit_must_not_exceed_debit flag is better suited for this scenario. Considering an account can't be updated what would be the best way to approach this?

Create new accounts with the flag that allows overdraft? And move over the balance from the old accounts? And associate the new accounts with any existing external lookup table? What about the transactions on the old account? Users don't typically expect to be issued new accounts because of a new feature.


Would it be recommended to not set any flag such as `flags.debits_must_not_exceed_credits` and just control the constraint outside tigerbeetle by maybe checking the account balance before transaction and applying any constraint necessary?

**Comment by matklad** [comment]
One meta observation here is that TigerBeetle Accounts and Transfers are _internal implementation detail_ Each user account and each user transfer could map to multiple account transfers. 

That is, your application should have some form of a schema that maps your domain object to TB's accounts&transfers. The schema can, of course, evolve over time, but it is the responsibility of the application to "migrate" the data (either through stop-the-world one-time migration, or incerementally, by merging both old and new accounts for some time). 

With this being said, the general pattern for solving any business-specific problem is to use auxiliary control accounts and a series linked transfers. We have several patterns documented for this:

https://docs.tigerbeetle.com/coding/#advanced-recipes

In particular https://docs.tigerbeetle.com/coding/recipes/balance-bounds I think is the pattern that can be specialized for  overdraft (though, we should add an explicit overdraft recipe)
