### ISSUE TITLE
Question about query operators

### ISSUE THREAD

**Issue by rudiservo** [tigerbeetle/tigerbeetle#2372]
Just an advice if you can turn on questions for the project.

Are there any query filter operators (and, or, not)?

The current filters are inherently "or" or "and" or depends on the field?

Can anyone change or add functionality to filters?

Thanks

**Comment by batiati** [comment]
Hello @rudiservo!
May I ask what kind of query you want to execute?

All query functions are currently _temporary_ APIs that will be replaced soon by the **query API** that will provide such functionality.
For now, the filter is intended to be simple without dealing with the complexity required by combining operators AND/OR/NOT in the correct precedence (e.g. `(debit_account_id=? OR credit_account_id=?) AND code=?`).

Also, feel free to join our [Community Slack](https://join.slack.com/t/tigerbeetle/shared_invite/zt-21xk62q7l-p~~G7~H01zQb88rQn7tWfQ)

**Comment by rudiservo** [comment]
@batiati thank you very much.
I am just trying to understand current limitations for current data model and if I wanted to add more models in the future for a personal project if I had to add those function to tigerbeetle or there would be some functionality built in for it.

But you where very informative, thank you.

BTW the slack link on the docs does not work.

**Comment by batiati** [comment]
Thanks for pointing out the Slack link!
Fixed here https://github.com/tigerbeetle/tigerbeetle/pull/2379 :rocket:
