### ISSUE TITLE
Java client TransferBatch.AMOUNT_MAX incorrect

### ISSUE THREAD

**Issue by tKe** [tigerbeetle/tigerbeetle#2396]
The current client is generated with the `AMOUNT_MAX` constant equal to the value of `170141183460469231740910675752738881536` (`0x00000000_00000080_00000000_00000080`) rather than the expected value of `340282366920938463463374607431768211455` (`0xffffffffffffffffffffffffffffffff`)

Should the constant instead be defined as `UInt128.asBigInteger(-1L, -1L);`?

https://github.com/tigerbeetle/tigerbeetle/blob/9cd85e3700715ee469797012c2fbd90ad896ddce/src/clients/java/java_bindings.zig#L110

**Comment by batiati** [comment]
Closed by https://github.com/tigerbeetle/tigerbeetle/pull/2398
Thanks!
