### ISSUE TITLE
Storing transfer comments in tigerbeetle?

### ISSUE THREAD

**Issue by michielbdejong** [tigerbeetle/tigerbeetle#241]
Suppose my application requires me to store, say, a 30-byte comment for each transfer that passes through my system. The `UserData` field only allows 16 bytes. Think for instance of a comment that explains what the transfer is for, like details about a purchase, the URL of some resource I paid for in a Web Monetization setting, or a user-defined message that was added to a bank transfer.

I understand that [best practice for storing UserData](https://docs.tigerbeetle.com/usage/data-modeling/#user_data) would be to store a random identifier in `transfer.UserData` and then use something like a key-value store alongside TigerBeetle where I store the actual comment, indexed by this same random identifier.
I could store the comment first, and only create the TigerBeetle transfer second, that would protect against states where a transfer exists but the comment cannot be retrieved.

Redis is a key-value store that can handle about 100,000 SETs per second. I guess I could use 10 Redis servers, or batch up the calls to Redis and still keep up with the 1,000,000 transfers per second that TigerBeetle supports.

Still, all of this feels like a lot of work. And I would be putting a second database system into my critical path.

Couldn't I just create zero-amount transfers where I store the rest of the bytes I need to store alongside the transfer, so that I can use TigerBeetle as the only database for transfer data?

Has anyone experimented with this?

**Comment by sentientwaffle** [comment]
As far as I know, no one has experimented with this (yet!). Most use a secondary database and don't actually need 1M transfers/second. And those without the secondary database haven't needed more than 16-bytes for extra data.

Just a few random thoughts for now:
- Right now we don't support 0-amount transfers (i.e. it triggers an error from the state machine). Though I guess you could just send money to a dummy account. (This does feel like a hack, though so does splitting comments between transfers.).
- You could use known (e.g. sequential) id [offsets](https://docs.tigerbeetle.com/usage/data-modeling/#identifier-offsets) for the extra transfers.
- If the comments are compressible with an application-known dictionary then maybe comments could be made to fit in 16 bytes. This wouldn't work as well for arbitrary user comments, though.

**Comment by michielbdejong** [comment]
IIUC there are now 2 datatypes in TigerBeetle, accounts and transfers, and both are 128-byte structs.
One could imagine a third datatype, which would have just a 16-byte id and then 112 bytes of user data.

Or alternatively, 2 extra data types, accountData and transferData, which would be allowed to appear in an accounts batch or a transfer batch respectively (and also be fetched alongside accounts or transfers respectively).

These data blobs would be "non-reactive", so you don't have to do anything with them other than store and retrieve them, although of course you should add the mechanisms to mark them as such, both in your database and in each of your client libraries.

On the positive side, that would make our life a lot easier, and actually make it possible to switch from Postgres to TigerBeetle as the backend of for instance [Prejournal](https://prejournal.org), to resolve [its slowness issue](https://github.com/pondersource/prejournal/issues/125). Without it, we can't switch away from Postgres, we can only add TigerBeetle in addition to Postgres.

But on the negative side, I also understand if you feel this would contaminate TigerBeetle's simplicity too much.

Let me know if you would consider accepting a PR along the lines of one of these two options! :)

**Comment by sentientwaffle** [comment]
We aren't at the "accept a PR" stage but we are discussing possibilities.

Just a little context around the 1 million transfers/second: often times a single "payment" corresponds to many different transfers (e.g. fees, currency exchange, etc). So the payment might be a single update in the foreign database, and have a "transfer amplification".

**Comment by jorangreef** [comment]
Thanks @michielbdejong — this is a great use case. As @sentientwaffle said, we're thinking about this. Thanks also for the link to Prejournal!

**Comment by michielbdejong** [comment]
Thanks for your answers!

For the Prejournal case I think we're in luck because it adheres to [CLOGS](https://michielbdejong.com/blog/26.html) - keeping a filesystem copy of all the source documents that feed into the ledger, and on-ledger we only need to refer to for instance an on-disk CSV filename + a line number within that CSV file. That can easily go in less than 16 bytes. I'll try to find time to refactor Prejournal on top of TigerBeetle and see if we can make it faster! :) -> follow-up in https://github.com/pondersource/prejournal/issues/125.

For our other product, "[Connect Your Books](https://connectyourbooks.com/) ([CYB](https://github.com/pondersource/CYB))" we do need more bytes but also it's not a system of record so we can probably just keep everything in memory and forget the data once it has passed through, so I think we're good for now.

Thanks again for building this amazing product, so exciting! :)
