### ISSUE TITLE
Running with --development doesnt print error message on panic

### ISSUE THREAD

**Issue by saltedpotatos** [tigerbeetle/tigerbeetle#2418]
I was updating my binary from 0.15.5 to 0.16.9 and re launched the binary  to see a panic

`./tigerbeetle start --addresses=3000 --development 1_1.tigerbeetle`
```sh
info(io): opening "1_1.tigerbeetle"...
warning(main): Grid cache size of 32MiB is small. See --cache-grid
info(main): multiversioning: disabled due to --development.
info(main): release=0.16.9
info(main): release_client_min=0.15.3
info(main): releases_bundled={ 0.16.9 }
info(main): git_commit=a082ff0237d5083f35e70d56c550ce271b6e4bf7
info(replica): superblock release=0.15.5
info(replica): 0: release_transition: release=0.16.9..0.15.5 (reason=open)
thread 3511012 panic: replica_release_execute unsupported
Unable to dump stack trace: debug info stripped
[1]    21282 abort      ./tigerbeetle start --addresses=3000 --development 1_1.tigerbeetle
```

but starting without the --development flag prints out an error message

`./tigerbeetle start --addresses=3000 1_1.tigerbeetle`
```sh
info(io): opening "1_1.tigerbeetle"...
info(main): release=0.16.9
info(main): release_client_min=0.15.3
info(main): releases_bundled={ 0.16.2, 0.16.3, 0.16.4, 0.16.8, 0.16.9 }
info(main): git_commit=a082ff0237d5083f35e70d56c550ce271b6e4bf7
info(replica): superblock release=0.15.5
info(replica): 0: release_transition: release=0.16.9..0.15.5 (reason=open)
error(main): 0: release_execute: release 0.15.5 is not available; upgrade (or downgrade) the binary
thread 3514491 panic: release not available
Unable to dump stack trace: debug info stripped
[1]    21540 abort      ./tigerbeetle start --addresses=3000 1_1.tigerbeetle
```

I haven't looked at the source yet, but I'm assuming the error message should also show when started with --development?

**Comment by sentientwaffle** [comment]
The actual error that occurs in this case differs depending on whether `--development` is set.

## With `--development`

When `--development` is set, multiversion binary auto-upgrades are disabled:

```
info(main): multiversioning: disabled due to --development.
...
info(replica): 0: release_transition: release=0.16.9..0.15.5 (reason=open)
thread 3511012 panic: replica_release_execute unsupported
```

...So to upgrade you would need to:

1. Stop the old binary.
2. Start the new binary _without_ `--development`.
3. Wait for it to complete the upgrade.
4. Then stop/start the new binary with `--development` again.

(This is somewhat awkward, but the expectation is that if you are using `--development` then it is not a production replica, so more often you would just recreate the database anyhow.)

## Without `--development`

Without `--development`, multiversion auto-upgrades are enabled.

However, there is a new error:

```
info(replica): 0: release_transition: release=0.16.9..0.15.5 (reason=open)
error(main): 0: release_execute: release 0.15.5 is not available; upgrade (or downgrade) the binary
thread 3514491 panic: release not available
```

This indicates that the version jump is too large -- the `0.16.9` binary only contains releases back to `0.16.2`:

```
$ ./tigerbeetle-0.16.9 version --verbose
...
multiversioning.header.past.releases={ 0.16.2, 0.16.3, 0.16.4, 0.16.8 }
```

`0.16.2` does include `0.15.5`, so you could upgrade in two steps (`0.15.5 → 0.16.2, 0.16.2 → 0.16.9`)

**Comment by saltedpotatos** [comment]
Thanks for the explanation!

**Comment by sentientwaffle** [comment]
Now that https://github.com/tigerbeetle/tigerbeetle/pull/2425 is merged, within a few releases it will be possible to instead upgrade a `--development` replica with:

1. Stop the old binary.
2. Start the new binary _with_ `--development`.
