### ISSUE TITLE
Increase in Cognitive Complexity due to Centralized Control Flow

### ISSUE THREAD

**Issue by smhmayboudi** [tigerbeetle/tigerbeetle#2445]
This approach to control flow management, though structured, may inadvertently inflate the cognitive complexity metric tracked by tools like "eslint-plugin-sonarjs". Centralizing if and switch statements within a parent function requires more conditions and decision points to remain in a single scope, which goes against best practices for reducing cognitive complexity by distributing conditional logic.

Proposed Solutions:

- Balance Centralization with Complexity Goals: Consider relaxing the guideline slightly to allow some branching logic in helper functions, especially if it can reduce excessive complexity in the main function.
- Incremental Refactoring: Regularly analyze functions with high cognitive complexity and break down particularly complex control flows where necessary.
- Alternative Metrics: Explore additional or alternative complexity metrics that align more closely with Tiger Style's control flow goals but do not penalize the centralized structure as harshly.

Implementing these adjustments may help in aligning Tiger Style's centralized control flow philosophy with cognitive complexity best practices, improving both readability and maintainability.

**Comment by smhmayboudi** [comment]
Centralizing control flow can make it easier to write targeted tests, as the main function becomes the single entry point for validating different conditions and outcomes. This approach ensures that control flow scenarios are thoroughly covered in one place, while helper functions, containing non-branching logic, are easier to unit test in isolation. However, the trade-off is a potential rise in cognitive complexity, as complex conditions accumulate in the parent function, increasing the effort required to understand and maintain the function's control flow.

**Comment by matklad** [comment]
We are quite happy with the rules as stated. Spreading out related decisions across several scopes makes the code harder to understand. What's worse, it frequently leads to the increase in the overall number of conditions, as it becomes harder to spot redundant logic.

It's not about how large or small the functions are, but rather about how well the logic is factored --- there are many ways to factor given code into the set of functions, and, usually, going for raw metrics like function length or cyclomatic complexity prevents finding the best factoring.
