### ISSUE TITLE
Latest golang client v0.16.11 doesn't work and crashes my whole app on Linux (Ubuntu,Mint) 

### ISSUE THREAD

**Issue by gladkikhartem** [tigerbeetle/tigerbeetle#2467]
1. Setup Tigerbeetle cluster inside docker based on this Page: https://docs.tigerbeetle.com/operating/docker/
2. Try to perform some transactions using latest Golang Client (v0.16.11)
```
	client, err := tb.NewClient(types.ToUint128(0), []string{"127.0.0.1:3002", "127.0.0.1:3001", "127.0.0.1:3003"})
	if err != nil {
		log.Printf("Error creating client: %s", err)
		return
	}
	defer client.Close()
	client.Nop()
```

The client then crashes whole app:
```
go run .
thread 42087 panic: session evicted
Unwind information for `:0x402b97` was not available, trace may be incomplete
```

**Comment by gladkikhartem** [comment]
go version go1.21.0 linux/amd64

lsb_release -a 
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera


cat /etc/os-release
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy

**Comment by sentientwaffle** [comment]
Hi @gladkikhartem,

You mention that the client is running v0.16.11 -- what version are the replicas running? It must be at least v0.16.11 or else the client will be incompatible.

**Comment by gladkikhartem** [comment]
@sentientwaffle I'm running latest Docker image using guideline  https://docs.tigerbeetle.com/operating/docker/

**Comment by gladkikhartem** [comment]
ghcr.io/tigerbeetle/tigerbeetle                                 latest           8f64c5f1180f   6 weeks ago     23.9MB

**Comment by gladkikhartem** [comment]
> It must be at least v0.16.11 or else the client will be incompatible.

Even if it's incompatible - I'm not expecting all my application crash in uncontrolled manner.

**Comment by sentientwaffle** [comment]
As of https://github.com/tigerbeetle/tigerbeetle/pull/2484 client eviction no longer panics the client.

**Comment by gladkikhartem** [comment]
![image](https://github.com/user-attachments/assets/52ae1842-72e1-43ee-a7e7-9a3ea6146314)
Testing with latest v0.16.13 - no more panics.

But it looks like I had to upgrade docker image for client to v0.16.13 to no longer panic an work correctly.

**Comment by sentientwaffle** [comment]
Yes, this was a client fix, so it required a client upgrade.
