### ISSUE TITLE
`tidy.zig` does not ignore commented lines when checking for banned `std` library usage

### ISSUE THREAD

**Issue by raghunandanbhat** [tigerbeetle/tigerbeetle#2473]
the function - `tidy_banned()` in `tidy.zig` does not ignore commented lines when checking for banned `std` library usage.`./zig/zig build test` fails if a file contains banned `std` library usage and it is commented. 

Is this intentional to discourage any mention of these parts of the `std` library, or would it be acceptable to update `tidy_banned()` to ignore commented lines?

**Comment by matklad** [comment]
tidy intentionally doesn't try to be a general tool --- it only works only for the specific code in this repository. The tidy logic is only made more complicated to solve a specific false positive.

We haven't seen a _specific_ need to exempt commented-out lines from checking.

If anything, we should add a tidy check to ban commented-out code...
