### ISSUE TITLE
Tigerbeetle Repl Client cannot access Tigerbeetle Server through virtual networking

### ISSUE THREAD

**Issue by ashley-nygaard** [tigerbeetle/tigerbeetle#2509]
I'm running into an issue trying to access Tigerbeetle via the SDK or Repl when the server is not directly on the same host.
I've created a VM of Ubuntu 22.04.5 Live Server arm64.
I have confirmed that I can host a static website via nginx from the VM and access the site on the host machine using port forwarding configuration in VirtualBox.
That confirms that the host can 'see' inside the VM.
Theoretically, with similar forwarding configuration for Tigerbeetle, I should be able to use the Repl to connect to Tigerbeetle running inside the VM.

When using the tigerbeetle-go client or the REPL from the host machine, I cannot access the running Tigerbeetle cluster.

The errors I receive are:

```plaintext
info(message_bus): peer performed an orderly shutdown: message_bus.MessageBusType(.client).Connection.Peer{ .replica = 0 }
```

and

```plaintext
error(message_bus): error receiving from message_bus.MessageBusType(.replica).Connection.Peer{ .replica = 0 }: error.ConnectionResetByPeer` when the client tries to connect.
```

When using Tigerbeetle and the client (or Repl) on the same machine everything connects as expected.

Expected Outcome:

Tigerbeetle to allow connections when the client is not on the same machine.

- VM
  - ubuntu-22.04.5-live-server-arm64
- Host
  - M1 Sonoma 14.0

**Comment by sentientwaffle** [comment]
Hi @ashley-nygaard -- can you share the snippet of code you used to initialize tigerbeetle-go?

Also, which versions of the replica and the client are you using? e.g. 0.16.x?

**Comment by ashley-nygaard** [comment]
Hi @sentientwaffle I'm trying the examples in the Quick Start.

For the Repl I'm using [this example](https://docs.tigerbeetle.com/quick-start#4-connect-to-the-repl):

```bash
./tigerbeetle repl --cluster=0 --addresses=3000
```

Then under the `tigerbeetle-go` client, I'm just using the connection example [here](https://docs.tigerbeetle.com/quick-start#4-connect-to-the-repl).

Anything above `tigerbeetle-go@0.16.1` and I get the following error:

```plaintext
warning(replica): 0: on_request: ignoring unsupported client version; too high (client=244598801749443206418031865540777813779 version=0.16.14>0.16.1)
error(replica): 0: sending eviction message to client=244598801749443206418031865540777813779 reason=client_release_too_high
info(message_bus): peer performed an orderly shutdown: message_bus.MessageBusType(.replica).Connection.Peer{ .client = 244598801749443206418031865540777813779 }
```

**Comment by sentientwaffle** [comment]
Replicas are only compatible with clients of the same version or older. That is, you can't use a newer client against an older server. I'd recommend upgrading your server to our latest release.

The reason that we use this approach is that it dramatically reduces the surface area that we need to test (and reason about) before each release. For production deployments, the idea is that you would always upgrade the cluster first, and then when the cluster is upgrade you could do a rolling upgrade of the clients.

**Comment by ashley-nygaard** [comment]
I have run through the [Quickstart](https://docs.tigerbeetle.com/quick-start) and I believe the versions are mismatched.

When trying to download the latest linux release I get this error. 
<img width="711" alt="Screenshot 2024-11-25 at 2 05 59 PM" src="https://github.com/user-attachments/assets/68dbb10e-1e87-462d-a1ab-3c646e439ebf">

So I used the Direct Download instead.
This is the version of Tigerbeetle running as a server on the VM. [Direct Download aarch64](https://docs.tigerbeetle.com/quick-start#direct-download)
<img width="401" alt="image" src="https://github.com/user-attachments/assets/cfdd7851-4de4-4d00-a58c-413c5de9bea5">

This is the version of the repl on the host: (Mac M1 Sonoma)
<img width="430" alt="Screenshot 2024-11-25 at 1 58 18 PM" src="https://github.com/user-attachments/assets/8b7f1a71-a526-4237-bdb6-2c9d6c7bf878">

How can I get the versions to match?

**Comment by sentientwaffle** [comment]
You can grab any of our current/past releases from [here](https://github.com/tigerbeetle/tigerbeetle/releases).
0.16.**14** was released today, so unless you upgrade your server you shouldn't upgrade the repl past [0.16.**13**](https://github.com/tigerbeetle/tigerbeetle/releases/tag/0.16.13).

Your replica running 0.16.13 should be already compatible with your (repl) client running 0.16.1, though.

Sorry that the quickstart installation failed! My guess is that it downloaded an x86_64 binary, and it looks like you're on aarch64.

**Comment by ashley-nygaard** [comment]
Great!
No connection errors are being thrown now!
However, no accounts are being created using the basic sample and there is no errors or outputs. How can I debug this?

```go 
package main

import (
	"fmt"
	"log"
	"os"
	"reflect"

	. "github.com/tigerbeetle/tigerbeetle-go"
	. "github.com/tigerbeetle/tigerbeetle-go/pkg/types"
)

// Since we only require Go 1.17 we can't do this as a generic function
// even though that would be fine. So do the dynamic approach for now.
func assert(a, b interface{}, field string) {
	if !reflect.DeepEqual(a, b) {
		log.Fatalf("Expected %s to be [%+v (%T)], got: [%+v (%T)]", field, b, b, a, a)
	}
}

func main() {
	port := os.Getenv("TB_ADDRESS")
	if port == "" {
		port = "3000"
	}

	client, err := NewClient(ToUint128(0), []string{port})
	if err != nil {
		log.Fatalf("Error creating client: %s", err)
	}
	defer client.Close()

	log.Println("client successfully created")

	// Create two accounts
	res, err := client.CreateAccounts([]Account{
		{
			ID:     ToUint128(1),
			Ledger: 700,
			Code:   1,
		},
		{
			ID:     ToUint128(2),
			Ledger: 700,
			Code:   1,
		},
	})
	if err != nil {
		log.Fatalf("Error creating accounts: %s", err)
	}

	for _, err := range res {
		log.Fatalf("Error creating account %d: %s", err.Index, err.Result)
	}

	fmt.Println("ok", client)

	transferRes, err := client.CreateTransfers([]Transfer{
		{
			ID:              ToUint128(1),
			DebitAccountID:  ToUint128(1),
			CreditAccountID: ToUint128(2),
			Amount:          ToUint128(10),
			Ledger:          700,
			Code:            1,
		},
	})
	if err != nil {
		log.Fatalf("Error creating transfer: %s", err)
	}

	for _, err := range transferRes {
		log.Fatalf("Error creating transfer: %s", err.Result)
	}

	// Check the sums for both accounts
	accounts, err := client.LookupAccounts([]Uint128{ToUint128(1), ToUint128(2)})
	if err != nil {
		log.Fatalf("Could not fetch accounts: %s", err)
	}
	assert(len(accounts), 2, "accounts")

	for _, account := range accounts {
		if account.ID == ToUint128(1) {
			assert(account.DebitsPosted, ToUint128(10), "account 1 debits")
			assert(account.CreditsPosted, ToUint128(0), "account 1 credits")
		} else if account.ID == ToUint128(2) {
			assert(account.DebitsPosted, ToUint128(0), "account 2 debits")
			assert(account.CreditsPosted, ToUint128(10), "account 2 credits")
		} else {
			log.Fatalf("Unexpected account")
		}
	}

	fmt.Println("ok")
}
```

**Comment by martijngonlag** [comment]
@ashley-nygaard if all accounts were created successfully, the response is an empty array (ref [response and errors](https://docs.tigerbeetle.com/clients/go#response-and-errors)). The lack of a response/error therefore is an indication that the code ran successfully. 

Can you confirm which version of `go` you are running? I copied your code and ran it against my local TB cluster and it worked as is:

```sh
$ go run 2509.go
2024/11/25 22:16:01 client successfully created
ok &{0x14c0084d0 {0 0}}
ok
$ go run 2509.go
2024/11/25 22:18:25 client successfully created
2024/11/25 22:18:25 Error creating account 0: AccountExists
exit status 1
```

Can you also check with the TB REPL to confirm whether the accounts/transfers exist or not? 
```sh
$ tigerbeetle repl --cluster=0 --addresses=3000
$ lookup_accounts id=1, id=2;
$ get_account_transfers account_id=1;
```

**Comment by ashley-nygaard** [comment]
@martijngonlag you are correct that the code above runs successfully if the TB client and server are on the same host. I am having issues trying to use the client on my Mac M1 Sonoma while the server is in the Ubuntu VM.

The client code does not indicate any errors or issues. I have also tested using the repl inside the VM to verify if the accounts were created. That results in: 
<img width="273" alt="Screenshot 2024-11-26 at 9 44 28 AM" src="https://github.com/user-attachments/assets/6ec160c9-392b-48a0-ab89-0c623164caf7">


I have verified using the repl client inside the VM can create accounts. I created an account with id=1. I would then expect to see the error you posted using the go client on the host (Mac). I don't see any errors. 

I'm using `go 1.23.2`

**Comment by martijngonlag** [comment]
@ashley-nygaard Strange; if the TigerBeetle client cannot connect to the replica I would expect a log line such as the below (which is what I got when I tested).

```sh
warning(message_bus): error connecting to replica 0: error.ConnectionRefused
```

I don't have a way to test in the exact same environment (I'm on an M3 Pro w/ Sequoia and use UTM for virtualization), however, the below steps worked successfully for me:

1. Install TigerBeetle in Ubuntu VM: `curl -Lo tigerbeetle-aarch64-linux.zip https://github.com/tigerbeetle/tigerbeetle/releases/latest/download/tigerbeetle-aarch64-linux.zip && unzip tigerbeetle-aarch64-linux.zip && ./tigerbeetle version`
2. Run `ip addr` in the Ubuntu VM to get the IP address
3. Start the TigerBeetle Replica in Ubuntu and set the `--addresses` parameter to the IP address of the Ubuntu VM (step 2): `./tigerbeetle start --addresses={ip_address}:3000 --development 0_0.tigerbeetle`
4. Set the `TB_ADDRESS` on your MacBook: e.g. `export TB_ADDRESS={replica_ip}:3000`
5. Run the code sample again

Can you try those steps? If they are not successful, please share the following so we can keep troubleshooting:

1. The IP address for the Ubuntu VM
2. The command used to start the TigerBeetle Replica
3. Results from running `telnet {ip_address} 3000` from your MacBook

**Comment by ashley-nygaard** [comment]
@martijngonlag 
Explicitly starting the server with the VM's local IP address seems to have solved the issue.
<img width="809" alt="Screenshot 2024-11-28 at 11 50 28 AM" src="https://github.com/user-attachments/assets/6e6d60ca-9b86-4b36-9e46-7dc3d572e72b">

 I'm able to connect the tigerbeetle-go client on the host via port forwarding to `127.0.0.1:3000`!

I believe this resolves my issue!

**Comment by martijngonlag** [comment]
@ashley-nygaard glad to hear it! I've opened a PR to add a note to the documentation for Docker to hopefully prevent others from having to spend time on this. I'll close this issue, but feel free to re-open, or open a new one, if you run into anything else!

**Comment by martijngonlag** [comment]
@ashley-nygaard quick update; it turns out I was incorrect in my previous updates. While the way I shared works, you don't actually have to specify the VM's IP address. Instead, you can start TigerBeetle with `--addresses=0.0.0.0:3000` and then use port-forwarding. This will work. If you only specify `--addresses=3000` it defaults to `127.0.0.1` which is why the quick start command didn't work for you as-is. 

Hope that clarifies things!
