### ISSUE TITLE
OK response is not returned from the client

### ISSUE THREAD

**Issue by mkadirtan** [tigerbeetle/tigerbeetle#2518]
The documentation states that:

| ok
| The account was successfully created; it did not previously exist.

| Note that ok is generated by the client implementation; the network protocol does not include a result when the account was successfully created.

link: https://docs.tigerbeetle.com/reference/requests/create_accounts/#ok

However, the go client doesn't return OK for successful results, instead it returns an empty list.

For reference, the following code from the Go client is responsible for returning the OK response, but c.doRequest returns 0 for wrote, for some reason - which seems like the heart of the issue. I also checked that the account was created, to be sure.

<img width="871" alt="image" src="https://github.com/user-attachments/assets/39b168cc-1451-4874-9ea2-64fe00690170">

**Comment by batiati** [comment]
Hello @mkadirtan!
Yes, that's the expected behavior as stated at https://docs.tigerbeetle.com/clients/go#response-and-errors.

However I agree 100% with you, that description for the `ok` results is rather misleading! Thank you for pointing it out!

**Comment by mkadirtan** [comment]
So, the documentation will change, but the behavior is correct, did I understand right?

**Comment by mkadirtan** [comment]
Oh, nevermind, I didn't check the link before replying, so the go client documentation is different from the generic documentation 👍
