### ISSUE TITLE
Separate the IO model into separate projects

### ISSUE THREAD

**Issue by dravenk** [tigerbeetle/tigerbeetle#2519]
Would you teams consider separating IO processing into a separate library? I am trying to use the code of the IO processing part of this project, and I have tried to separate the IO processing code, and have run most of the test code.
https://github.com/zon-dev/aio

**Comment by dravenk** [comment]
This processing model may help power some network frameworks

**Comment by matklad** [comment]
See https://github.com/tigerbeetle/tigerbeetle/issues/1988#issuecomment-2150580158!

TL;DR: no, but community is welcome to do it!
