### ISSUE TITLE
Build tests on various distros only happens for Node client, not other clients

### ISSUE THREAD

**Issue by eatonphil** [tigerbeetle/tigerbeetle#252]
The Node client has some scripts to test that it is installable on 6 major distros. The other clients don't yet have that.

We should have the same sort of scripts that test installability for every client.

**Comment by eatonphil** [comment]
@sentientwaffle I don't think we run cross-distro tests for the Go or C# client (the latter maybe not as important, but the Go one is)

**Comment by sentientwaffle** [comment]
Oops, this got auto-closed when https://github.com/tigerbeetledb/tigerbeetle/pull/284 merged.

**Comment by matklad** [comment]
decided to not do this: this is a test for how to install node on distro x, not for how tigerbeetle works on distro x. We test on alpine, ubuntu, windows and mac, which gives us enough confidence that things generally work
