### ISSUE TITLE
Multi-tenant Use Case and Get Account Balances

### ISSUE THREAD

**Issue by mkadirtan** [tigerbeetle/tigerbeetle#2525]
I'm trying to experiment with multi-tenant use cases of the Tigerbeetle. As stated in the docs, I am using Ledger to separate accounts between tenants. Ledger is a uint32, and in my use case I used 16 bits for tenant namespace, and 16 bits to allow tenants to use and define their own ledgers. So, a uint32 Ledger in Tigerbeetle is a combination of uint16 Tenant's own ledger and uint16 Tenant's id in my example.

I can enforce Tenant boundaries on all the commands available in the Tigerbeetle, except one: get_account_balances.

The reason is, that I can't use Ledger in AccountFilter, and the returned response doesn't contain any account information. For example, get_account_transfers also uses AccountFilter, but I can check that returned transfers are in the tenant's ledger. Such a use case is not possible in get_account_balances, and I might query the accounts based on the available filter before getting balances but I wanted to ask you guys, is there a better way I can do this, today or in the future?

**Comment by batiati** [comment]
Hi @mkadirtan!

The operations `get_account_transfers/balances` are tied to a single account, so the `ledger` will always obey the account's ledger. The case of `get_account_balances`, each balance `timestamp` corresponds to the account's balance after a transfer with the same timestamp, so you can join the results of `get_account_transfers` and `get_account_balances` at the application side (both operations accept the same filter and guarantee matching results).

Note that those operations are part of a temporary API, we plan to release a more comprehensive query API that will allow multiple accounts at the same call (and the proper way to indicate which account/ledger the result belongs to).

**Comment by mkadirtan** [comment]
I didn't know it was tied to a single account, that covers my use case until the new API, thanks!
