### ISSUE TITLE
Add deallocation and deinitialization to the repl

### ISSUE THREAD

**Issue by brson** [tigerbeetle/tigerbeetle#2528]
The entire repl assumes it is using arena allocators and neither deallocates nor runs deinit functions. As the repl grows, this is looking wrong, and opens the door to future bugs.

We should add deinit methods, calls to deinit and free on errdefer, etc.

**Comment by brson** [comment]
This probably needs to be done before or at the same time as https://github.com/tigerbeetle/tigerbeetle/issues/2528

**Comment by matklad** [comment]
> This probably needs to be done before or at the same time as #2528

@brson 2528 is _this_ issue, did you perhaps have something else in mind? Or just enjoying the freedom of creating self-referential data structures while rustic doesn't look? :D 

> We should add deinit methods, calls to deinit and free on errdefer, etc.

It would also be great to check if we can design this away! It feels like REPL should have well-known static limits on, eg, how long a single command could be. That means that we should be able to pre-allocate worst-case data structures and avoid any dynamism.

So the parser, shouldn't parse stuff into freshly allocated objects, and rather just fill-in an out parameter.

**Comment by brson** [comment]
> @brson 2528 is _this_ issue, did you perhaps have something else in mind? Or just enjoying the freedom of creating self-referential data structures while rustic doesn't look? :D

Oops. I meant https://github.com/tigerbeetle/tigerbeetle/issues/2515

**Comment by brson** [comment]
> It would also be great to check if we can design this away! It feels like REPL should have well-known static limits on, eg, how long a single command could be. That means that we should be able to pre-allocate worst-case data structures and avoid any dynamism.

We're moving in that direction. On master most of the repl (except the parser) now preallocates fixed size slices and ArrayLists for its buffers; and https://github.com/tigerbeetle/tigerbeetle/pull/2542 looks to do more, including converting some ArrayLists to BoundedArrays.

Even with e.g. preallocated ArrayLists, I assume we would still want deinit methods to free them.

**Comment by matklad** [comment]
>Even with e.g. preallocated ArrayLists, I assume we would still want deinit methods to free them.

Yup, but perhaps we don't need array lists and can use something as simple as 

```
transfers: [transfers_max]Transfer = undefined;
transfer_count: usize = 0;
```

This is perhaps irrational on my part, but I am not a huge fan of ArrayLists or BoundedArrays --- open-coded array with a count often feels simpler!
