### ISSUE TITLE
Does the balancing debits recipe work on 0.16?

### ISSUE THREAD

**Issue by michael-groble** [tigerbeetle/tigerbeetle#2546]
https://docs.tigerbeetle.com/coding/recipes/multi-debit-credit-transfers#multiple-debits-single-credit-balancing-debits

I can make this work on 0.15.6, meaning I see an `exceeds_credits` error.  but don't get any errors on 0.16. For example, if I only provide 50 in `A`, then at the end, I'll see 50 debits in `A` and 100 credits in `X`. Is there a way to perform the same example in 0.16? I see the [tracking issue](https://github.com/tigerbeetle/tigerbeetle/issues/2231) references zero-amount transfers, but doesn't mention balancing debits so wanted to check.

**Comment by michael-groble** [comment]
ahh, I think I answered my own question.  I seem to be able to do it if I add a new `credits_must_not_exceed_debits` account to act as a "shortage" and another `debits_must_not_exceed_credits` to act as a "threshold" for that shortage.

**Comment by martijngonlag** [comment]
Hi @michael-groble, sorry to hear you are experiencing some issues! I have tried the recipe against `0.16.17` and I got the `exceeds_credits` error as expected. To troubleshoot this further, can you provide the following bits of information? 

- Which client are you using?
- Which `0.16.n` version are you using?
- A copy of the `create_accounts` and `create_transfers` you are running

**Comment by matklad** [comment]
Good catch, the recipe as stated definitely does not work, and that's because there's a bug in the recipe: 

https://github.com/tigerbeetle/tigerbeetle/pull/2576

In the last step, it is required to try to send `ammount_max`, not 100. We had a test for this functionality, and the test was correct, but we messed up encoded the tested scenario in the docs!
