### ISSUE TITLE
Node Client 0.16.16 'panic: attempt to use null value'

### ISSUE THREAD

**Issue by bakerg** [tigerbeetle/tigerbeetle#2547]
Hi there,

We're seeing an issue approximately once a day where the node client will panic and exit, also causing the node process to crash.
```
thread 25 panic: attempt to use null value
/home/runner/work/tigerbeetle/tigerbeetle/src/clients/node/node.zig:287:27: 0xffff800910db in on_completion (tb_nodeclient)
???:?:?: 0x1625651f in ??? (???)
Unwind information for `???:0x1625651f` was not available, trace may be incomplete
```
Unfortunately we don't seem to be able to get more information on the crash into our monitoring.
We're currently on 0.16.16 but have now noticed that this was occurring with similar frequency on 0.16.11 and potentially earlier. Node version is 22.11

**Comment by cb22** [comment]
Thanks for the report, @bakerg - we're looking in to this!
