### ISSUE TITLE
LSM: remove_from_memory

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#262]
## Background

When a key is removed from the LSM, a tombstone is created. This tombstone is eventually compacted down to the last level of the tree, at which point it is dropped.

The accounting state machine commits `linked` account/transfer chains by executing each member in sequence — if an error is encountered, it rolls back the chain. "Rolls back the chain" here means it removes the new account/transfer from the groove, creating tombstones.

This is correct, but not optimal. We are creating tombstones in the object tree. Typically the object tree will be compacted by the move-table optimization (moreso after https://github.com/tigerbeetledb/tigerbeetle/issues/255), which doesn't read the data blocks, so the tombstones are never dropped, even at the last level.

## Tasks

When we know the key being removed exists _only in the mutable table_ we can remove it without creating a tombstone.

- See https://github.com/tigerbeetledb/tigerbeetle/issues/262#issuecomment-1320510077
- ~Add `Tree.remove_from_memory()` which removes the key from the mutable table.~
- ~Add `Groove.remove_from_memory()`.~
- ~`StateMachine` can call `remove_from_memory()` instead of `remove()` when it knows that the key being removed cannot possibly have existed prior to the current batch. So `remove_from_memory` corresponds to `put_no_clobber`.~

With these changes, we can also add `Tree.put_no_clobber`, which is just like `Tree.put` except it first asserts that `tree.lookup_from_memory` for the new key returns null. (We can't do this right now because `lookup_from_memory` might return a tombstone). i.e. `put_no_clobber`'s contract becomes stricter — right now it is "the corresponding key either no value or a tombstone", but it can be "the corresponding key has no value".

**Comment by jorangreef** [comment]
To emphasize also the invariant that we need to be careful in case a previous version of the key exists in the mutable table from a previous batch.

It would be great if the tree can handle this case safely regardless of state machine, on behalf of the state machine.

**Comment by sentientwaffle** [comment]
> To emphasize also the invariant that we need to be careful in case a previous version of the key exists in the mutable table from a previous batch.
>
> It would be great if the tree can handle this case safely regardless of state machine, on behalf of the state machine.

Excellent point! I assumed we needed to allow `Groove.remove()`s for keys which were not prefetched, but it looks like we already forbid that:

```zig
fn remove(groove: ...) void {
    ...
    assert(groove.prefetch_objects.removeAdapted(object.id, PrefetchObjectsAdapter{}));
}
```

---

Instead of exposing `Groove.remove_from_memory()`, `Groove.remove()`'s implementation can opportunistically/automatically skip creating a tombstone. Like so:

- Right now we only insert into `prefetch_ids` when `tree.lookup_from_memory` misses. Instead, always insert the id.
- Right now we clear `prefetch_ids` when the prefetch finishes. Instead, leave it intact.
- Since we always insert the id, don't `lookup_from_memory` in `Groove.prefetch_enqueue`. Instead, call `lookup_from_memory` from within the prefetch.
  - Or maybe combine `Tree.lookup_from_memory` and `Tree.lookup_from_levels` (I have been on the fence about this anyway) and call it from within the prefetch.
  - The only issue here is that we don't want to cause unnecessary delays by `IO.wait`-ing unless we are _actually_ waiting on IO, but we still need to avoid a stack explosion due to sync callbacks.

Then `remove()` skips creating a tombstone iff the key is in `prefetch_ids` but _not_ in `prefetch_objects`.

**Comment by sentientwaffle** [comment]
:thinking: ~This optimization is only valuable for tables which use the [move-table optimization](https://github.com/tigerbeetledb/tigerbeetle/issues/272).~

~But move-table will occasionally coalesce instead — and it will be forced to coalesce at the last level because the [table size increases](https://github.com/tigerbeetledb/tigerbeetle/issues/271). Since we will drop the tombstones then, maybe that is good enough — insert-then-immediately remove shouldn't be very common anyway.~

:arrow_down:

**Comment by jamii** [comment]
The lack of this causes a lot of extra compaction traffic in balance updates. Even if we're only transferring between two accounts we'll still fill up the balance tables and then spend time compacting them. 

In the trace below, compacting the redundant tombstones in the balance trees takes 853ms. The next slowest table is Transfer which only takes 104ms. This is on the critical path so we're taking an 8x slowdown on this op.

That's an extreme case, but we'll probably see smaller slowdowns for frequently updated balances like sales tax accounts.

![screenshot_2022-12-07_13-28-50](https://user-images.githubusercontent.com/340884/206323173-8a60819b-44bf-4b11-b96c-d675012ae051.png)

**Comment by matklad** [comment]
Fixed (secondary_index optimiazation)
