### ISSUE TITLE
LSM: Remove PostedGroove

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#264]
Make `Groove` flexible enough so that the separate `PostedGroove` type is no longer needed.

See: https://github.com/tigerbeetledb/tigerbeetle/blob/85dc0a70fccc86294208d4e957901aa675059cf7/src/lsm/posted_groove.zig#L20

As part of this, the StateMachine's PostedGroove should be indexed by `timestamp`, not `id` (unless there is a reason for using `id` that I am missing).

**Comment by cb22** [comment]
Fixed by #966 :tada:
