### ISSUE TITLE
LSM/Compaction: Beat Pacing and Scheduling

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#269]
- [ ] Perform a fixed (deterministic) amount of work _each beat_. (Instead of having to catch-up at the end of the measure.)
- [ ] Spread compaction work as evenly as possible across beats.
- [ ] Do not compact multiple levels _of a particular tree_ concurrently.
  - (This automatically fixes the last determinism issue mentioned in https://github.com/tigerbeetledb/tigerbeetle/pull/247 §3).
  - As part of this, the new minimum `lsm_batch_multiple` will be `8` (up from `4`).
- [ ] Minimize the number of concurrent compactions (trees).
  - For example, if there are 3 compactions that must run in a particular measure, run them in sequence instead of concurrently.
  - Of course, we can't _always_ run _all_ compactions in sequence, because in the (improbable) worst case there are `lsm_levels * tree_count`.
  - This helps group writes by time-of-death (see ["The Unwritten Contract of Solid State Drives"](https://pages.cs.wisc.edu/~jhe/eurosys17-he.pdf)).
  - It also reduces the buffer overhead of compaction (each compaction requires 3 blocks of buffer space). Fewer concurrent compactions → less memory required → more memory for compaction → faster.
  - This also reduces block address fragmentation due to freeset address reservation. Which in turn reduces space amplification.

**Comment by jamii** [comment]
Read/write iop usage during a single measure.

![image](https://user-images.githubusercontent.com/340884/224161737-6839d5b6-b999-474d-b416-395043dc090f.png)

A lot of empty space as some compactions finish and just a few are left running.

**Comment by jamii** [comment]
Also noticed that:
* In the first 31 ops we typically do one compaction tick per tree.
* Every 32nd op we do the remaining ~2k ticks.

**Comment by jorangreef** [comment]
Yes, finishing the remaining work on the last tick is a temporary hack, and what we should fix in compaction pacing, to spread the work across the measure.

**Comment by matklad** [comment]
We have the basics of this in I think?
