### ISSUE TITLE
LSM/Compaction: CPU/IO Pipelining

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#270]
## Background

Currently, compaction proceeds roughly like this (sequentially):

1. Read some blocks. (IO).
2. Sort-merge the blocks (CPU).
3. Write the output blocks and start the next set of reads (IO).

But this leaves disk throughput unused during the sort-merge.

## Solution

As described in [Pipelined Compaction for the LSM-tree](https://www.comp.nus.edu.sg/~hebs/pub/zigangpipe_ipdps14.pdf), we should instead:

1. Read some blocks. (IO).
2. Start the next set of reads, _then_ sort-merge the blocks (IO/CPU).
3. Write the output blocks. (IO).

... so that the next set of reads can begin working during the CPU sort-merge.

To determine how many blocks can be pre-read for the next round (after reading some blocks, but before the sort-merge takes place), use the last buffered key of every data block in levels A/B to compute how many data blocks will actually be consumed by the sort-merge, vs how many have to wait until the next set of reads.

**Comment by matklad** [comment]
Fixed!
