### ISSUE TITLE
LSM/Compaction: Table Scale

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#271]
## Background

Currently, all tables are 64MiB size (max).

When the immutable table is flushed, we rewrite up to `lsm_growth_factor * table_size_max = 8 * 64MiB` of level 0 (for each tree!).

## Solution

To [minimize write amplification](see <https://github.com/tigerbeetledb/tigerbeetle/pull/244>):

- Each tree has its own max table size.
- A tree's table size max is equivalent to the size of the immutable table (measured in number of values — the actual on-disk table is larger due to index/filter blocks and padding).

### Last Level

Reducing the table size makes the metadata cost (manifest overhead in-memory and on-disk) proportionally higher — we would either have to increase memory requirements (to accommodate many more tables in the `ManifestLevel`) or reduce the capacity of the tree.

Instead, let the _last_ level of the tree keep a 64MiB table size. Since the table count of each level increases exponentially, the last level holds the majority of the tree's capacity. Since the last level is only ever the output of a compaction (never input), it benefits from the granularity of the smaller input tables — compactions to the last level will rewrite fewer than `lsm_growth_factor` tables.

**Comment by jamii** [comment]
https://github.com/tigerbeetledb/tigerbeetle/pull/485 implemented the varying size per tree. 

Making the tables on the last level bigger has some open design questions (see https://github.com/tigerbeetledb/tigerbeetle/pull/485#issuecomment-1440666732). On slack we estimated that the current metadata cost per 1e9 transfers is only 2-3mb, so we can likely get away without the additional complexity of a larger last level for now.
