### ISSUE TITLE
LSM/Compaction: Move Table

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#272]
When the input table from level A does not overlap with any tables on level B, "move" it instead of merging it value-by-value.

A "move" is simply an update to the table's `level` in the manifest.

Adjacent tables that are less than their full size should be coalesced so that levels don't fill up with tiny partial tables (which would add too much metadata overhead).

**Comment by matklad** [comment]
I think we already have move table. We don't have move data_block though, but that's different.
