### ISSUE TITLE
CLI: Cache sizes

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#276]
[These 3 config values](https://github.com/tigerbeetledb/tigerbeetle/blob/d15acc663f8882cb02413129e8351bf3238335e6/src/config.zig#L50-L67) are currently defined at compile-time. Instead:
- They should be added as CLI arguments (`--cache-accounts`, `--cache-transfers`, `--cache-transfers-posted`) to `cli.zig`'s `start` command, and plumbed through to `main.zig` where they are passed to `replica.open()` via `state_machine_options`.
- Right now those config values are counts — but as CLI arguments they should be sizes (i.e. bytes) instead (parsed via `parse_size`). Before passing to `replica.open()`, we convert the size to a count (using e.g. `@sizeOf(Account)`), rounded down to a power-of-2 (due to `SetAssociativeCache`'s requirements).
- Leave the counts in `config.zig` and use them as the default value if the respective CLI arg isn't provided.

These new flags supersede the (partially implemented) `--memory` flag, which can be removed.

**Comment by matklad** [comment]
Question: am I correct that these config values are properties of the replica, and not of the cluster? That is, that different replicas in a cluster can run with different cache sizes?

**Comment by sentientwaffle** [comment]
Correct

**Comment by matklad** [comment]
closed by https://github.com/tigerbeetledb/tigerbeetle/pull/282
