### ISSUE TITLE
Clean up stray event loops

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#285]
Various functions (eg Replica.open) have their own internal event loops so they appear sync from the outside. Consolidate all of these into one event loop per `main` function.

**Comment by jamii** [comment]
Also relevant - a lot of tests/fuzzers tick through state changes synchronously (eg https://github.com/tigerbeetledb/tigerbeetle/blob/main/src/lsm/tree_fuzz.zig#L183-L188). I'm a little paranoid that because of this they don't have the same concurrent behavior as the full system.

**Comment by matklad** [comment]
This feels _mostly_ fixed. Maybe not at 100%, but I personally no longer feel like this bites us painfully.
