### ISSUE TITLE
IO: on_next_tick

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#292]
Implement an `IO.on_next_tick` (or maybe on `Storage`?).

Use it to fix the call sites where we synchronously invoke an async callback, e.g. https://github.com/tigerbeetledb/tigerbeetle/blob/a563d521674b0030961f4cc8cc5a2c6e16e98fd5/src/lsm/tree.zig#L299

**Comment by kprotty** [comment]
Closed by #319
