### ISSUE TITLE
StateMachine: Close account

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#294]
Depends on https://github.com/tigerbeetledb/tigerbeetle/issues/255

## Semantics

- Add a new account flag: `closed`.
  - Creating a _new_ account with `flags.closed=true` returns an error: `CreateAccountResult.closed_must_be_false`
- Add two new transfer flags: `close_debit_account` and `close_credit_account`.
  - To close an account, call `create_transfers`, with `flags.close_debit_account` and/or `flags.close_credit_account` set.
  - Closing transfers _may_ have a zero amount.
  - If `flags.close_debit_account` is set:
    - If `dr.debits_pending ≠ dr.credits_pending`, return `CreateTransferResult.closed_debit_account_pending_balance_must_be_zero`.
    - If `dr.debits_posted ≠ dr.credits_posted`, return `CreateTransferResult.closed_debit_account_posted_balance_must_be_zero`.
  - If `flags.close_credit_account` is set:
    - If `cr.debits_pending ≠ cr.credits_pending`, return `CreateTransferResult.closed_credit_account_pending_balance_must_be_zero`.
    - If `cr.debits_posted ≠ cr.credits_posted`, return `CreateTransferResult.closed_credit_account_posted_balance_must_be_zero`.
- Creating a transfer that has a closed {debit,credits} account returns an error: `CreateTransferResult.{debit,credit}_account_closed`.

## Implementation

- When closing an account, don't mutate the `Account` object tree.
- Instead store the `closed` status in the [balance tree](https://github.com/tigerbeetledb/tigerbeetle/issues/255).
- When re-assembling an Account from the 2 trees, include its `closed` status.

## Questions

- Should there be a secondary index on `closed`?
- Are there better error code names we could use?

<details>
<summary>(Superseded original proposal)</summary>
Depends on https://github.com/tigerbeetledb/tigerbeetle/issues/255

## Semantics

- [ ] Add a new account flag: `closed`.
- [ ] To close an account, call `create_accounts` with an existing account, with `flags.closed=true`.
  - [ ] Creating a _new_ account with `flags.closed=true` returns an error: `CreateAccountResult.closed_must_be_false`
  - [ ] The close-account's fields must match the existing account _or_ be zero (similar to how posting/voiding transfers match against pending transfers). (`closed_account_has_a_different_…`).
  - [ ] To close an account, the `debits_pending` must equal `credits_pending`, otherwise fail with `CreateAccountResult.closed_pending_balance_must_be_zero`.
  - [ ] To close an account, the `debits_posted` must equal `credits_posted`, otherwise fail with `CreateAccountResult.closed_posted_balance_must_be_zero`.
- [ ] Creating a transfer that has a closed {debit,credits} account returns an error: `CreateTransferResult.{debit,credit}_account_closed`.

## Implementation

- When closing an account, don't mutate the `Account` object tree.
- Instead store the `closed` status in the [balance tree](https://github.com/tigerbeetledb/tigerbeetle/issues/255).
- When re-assembling an Account from the 2 trees, include its `closed` status.

## Questions

- Should there be a secondary index on `closed`?
- Are there better error code names we could use?
</details>

**Comment by jorangreef** [comment]
Accounting has the concept of a “closing transfer” where you transfer the net balance to another account, but might (or might not) continue to post further transfers in new accounting periods.

Using a transfer in this way, would have some advantages:
* Help achieve the draining of the account, not only the enforcing of it.
* No need for `create_account`, which seems like it should only be used for creating accounts.
* The decision to permanently close the account could be a qualification flag, sometimes it's useful to only drain balances but not necessarily close, and vice versa.

**Comment by batiati** [comment]
And one more to this list:

- Using a linked transfer, one can guarantee that the account will be closed atomically with other related transactions.

**Comment by sentientwaffle** [comment]
Agreed that `create_transfers` would be a better interface. Just to check my understanding, we would add these two flags:

- `Transfer.flags.close_debit_account`
- `Transfer.flags.close_credit_account`

For a transfer to be created with these flags, the debit/credit account (respectively) must have a zero balance after the transfer. (We should probably allow zero-amount balances when closing an account, since its balance may already be zero).
When the transfer is created, we mark the debit/credit account (respectively) as permanently closed — any future transfers involving that account will fail.

For non-permanently closing a account we don't need a new flag.

(Aside: Using transfers also has the benefit of being able to leverage two-phase transfers in combination with closing accounts.)

**Comment by sentientwaffle** [comment]
I updated the Issue description with a new proposal (to trigger closing via transfers) — please give it another look.

**Comment by matklad** [comment]
fixed in https://github.com/tigerbeetle/tigerbeetle/pull/2234
