### ISSUE TITLE
Client: Auto-generate C header bindings for language clients.

### ISSUE THREAD

**Issue by kprotty** [tigerbeetle/tigerbeetle#298]
We're now auto-generating the `tb_client.h` C header #223 in source, but this can still go out of sync with either the headers or the source code in the language clients (`src/clients/*`). Write a script (preferably in Zig?) which auto-generates the C bindings for each of the language clients if possible.

- [X] dotnet
- [X] go
- [X] java
- [X] node

**Comment by batiati** [comment]
It's an excellent idea, you can assign me to that if you wish.

- Dotnet client: it will be really handy, we can generate all C# interop code from Zig.
- Java client: we already ref the `tb_client.zig` file in the JNI layer, but we can generate Java code for enums and get/set declarations from Zig.
- Node client: similar to the Java client, we can generate JS `export`s from a zig script.
- Go client: CGO already uses the generated `tb_client.h` file, but still there are a lot of decls in `types/main.go` that can be generated.

**Comment by batiati** [comment]
Closed by #600
