### ISSUE TITLE
u128s from the go client have the wrong endianness.

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#331]
Not sure whether the error is in the string->u128 conversion or the network code, but this hacky diff resulted in the correct ids arriving in the storage engine:

``` diff
diff --git a/samples/basic/main.go b/samples/basic/main.go
index 8387ca0..b054c6a 100644
--- a/samples/basic/main.go
+++ b/samples/basic/main.go
@@ -8,12 +9,19 @@ import (
        tb_types "github.com/tigerbeetledb/tigerbeetle-go/pkg/types"
 )

+func reverse(s [16]byte)  [16]byte {
+    for i, j := 0, len(s)-1; i < j; i, j = i+1, j-1 {
+        s[i], s[j] = s[j], s[i]
+    }
+    return s
+}
+
 func uint128(value string) tb_types.Uint128 {
        x, err := tb_types.HexStringToUint128(value)
        if err != nil {
                panic(err)
        }
-       return x
+       return tb_types.BytesToUint128(reverse(x.Bytes()))
 }
```

**Comment by eatonphil** [comment]
Ah, that's my code. Embarrassing. Feel free to make the change and add a test?

**Comment by eatonphil** [comment]
Actually, there are tests for it already (run `go test`). Maybe there was a case I missed.

**Comment by jamii** [comment]
The bug is not in your code, it's somewhere in the client package. I just reverse the bytes in your code because I don't know how to do anything in go.

**Comment by jamii** [comment]
``` zig
pub fn main() !void {
    const i: u128 = 0x112233;
    std.debug.print("{any}", .{@bitCast([@sizeOf(u128)]u8, i)});
   // prints { 51, 34, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
}
```

``` go
func main() {
  fmt.Println("%s", uint128("112233").Bytes());
  // prints [51 34 17 0 0 0 0 0 0 0 0 0 0 0 0 0]
}
```

So that much seems ok.

**Comment by jamii** [comment]
This only affects uint128. Smaller integer types are transmitted correctly. But as far as I can tell there is no marshaling - we just stick all the integers into an extern struct and bitcast it.

**Comment by jamii** [comment]
Uh, I'm dumb - the stuff I printed above was *with* the bytes reversed. Fix incoming :S
