### ISSUE TITLE
Proposal: separate acquiring a cache block from creating a cache entry.

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#353]
Currently, the sequence for a grid read is:
* Create a cache entry with an uninitialized block. (This must not evict `locked` entries, so we must limit concurrent reads to `cache.ways - 1`.)
* 'Lock' the cache entry.
* Schedule the read .
* When the read completes, the block is initialized.
* Call the read callback.

We could instead have a pool of cache blocks and only store pointers in the cache. Then the sequence would be:
* Acquire a cache block.
* Schedule the read.
* When the read completes, the block is initialized.
* Create a cache entry with the initialized block. This may evict another entry, releasing it's cache block back into the pool (via an `on_evict` callback in the cache).
* Call the read callback.

As long as we never accidentally nest read callbacks this maintains the invariant that the cache block is always valid for the duration of the callback. (We could assert this by setting a boolean flag on the grid before running the read callback and clearing it afterwards).

Benefits:
* No uninitialized values in the cache, making gnarly bugs like https://github.com/tigerbeetledb/tigerbeetle/pull/346/files impossible.
* Removes the need for a locking api in the cache. Makes inserting grid cache entries slightly cheaper because we don't need to scan the read queue.
* Decouples `Grid.read_iops_max` from the cache, allowing us to increase the read queue depth without changing the cache layout.

**Comment by jorangreef** [comment]
What would the cons be?

For example, if I understand correctly, this would mean pointer-chasing, not only the cache miss to the pointer, but a second cache miss also to the block?

**Comment by jamii** [comment]
Yes, one extra pointer hop per successful cache lookup. But `grid.read_iops_max` fewer pointer lookups to check for locked entries on insert. And avoids the extra write to the block in https://github.com/tigerbeetledb/tigerbeetle/pull/346 to set the address on cache insert.

**Comment by jamii** [comment]
Oh, actually we check if entries are locked repeatedly in the eviction loop, so in the best case `grid.read_iops_max` and in the worst case `grid.read_iops_max * safety_count` pointer lookups.

**Comment by kprotty** [comment]
> Makes inserting grid cache entries slightly cheaper because we don't need to scan the read queue.

Could this part be elaborated on? I assume it refers to the `assert_not_reading` in `Grid.write_block`

**Comment by jamii** [comment]
`assert_not_reading` will still be necessary. But we can get rid off https://github.com/tigerbeetledb/tigerbeetle/blob/main/src/lsm/grid.zig#L482, which prevents the cache from evicting a block that is being referenced from an in-progress read, and is potentially called many times per insert.

**Comment by jorangreef** [comment]
This is a nice design @jamii — the current locking is hairy and this will simplify it. If you don't see another way to avoid the cache miss then let's go for it.

**Comment by jamii** [comment]
There are attempts in jamii-cache-pool and jamii-cache-pool-conservative.

jamii-cache-pool has to queue all reads so that it's safe to evict from the cache to free up a block. It's not able to decouple read_iops_max from ways in the end, because it can only guarantee that a block can be evicted from a set if there are less pending reads than ways in that set. It could be tweaked to evict from any set, but that's starting to feel risky. 

jamii-cache-pool-conservative doesn't have to evict. Instead it reserves `read_iops_max` for pending reads. This isn't *as* bad as it sounds, because the current design effectively reserves `read_queue.len <= read_iops_max` entries in the cache.

Both get to look in the cache before looking for pending reads in the queue, which the current design can't safely do, so the one extra pointer hop in cache lookup is offset by avoiding `sum([iop.reads.len for iop in read_iops])` pointer hops to check the read queue.

Also one upside of queuing all reads is that we don't have a gap between looking in the cache and running a callback on the cached value, so there's no possibility of the cache entry disappearing in between and forcing a retry, which simplifies scheduling. It also cuts p100 latency by 25% in `zig build benchmark` with 100 batches, but I think this is essentially noise - only one compaction gets faster.

Apart from that neither branch has any measurable perf difference at the moment because we don't make good use of io concurrency anyway. So I think it makes sense to first look at io scheduling and maybe compaction pacing, and then return to this once we have a clearer picture of the tradeoffs.

**Comment by kprotty** [comment]
Closed by #365
