### ISSUE TITLE
Switch to a better code review tool

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#369]
Wishlist:
1. Allow marking individual hunks as read (github only allows marking entire files as read).
2. Making a one line change to a file just shows that new hunk as unread (github marks the entire file as unread and doesn't show the diff).
3. Can comment on lines that were not changed (eg "You need to change this function to match your other changes" - github won't allow this comment unless it happens to be near a changed line).
4. Can view and comment on the PRs version of a file (github allows viewing the file, but you have to go back to the patch view to comment).
5. Allow jumping from a comment in the conversation view to the corresponding line in the patch view (github for some reason just doesn't have this feature).
6. Links to specific lines in the patch view actually work (in github patches are often collapsed by default, so the url anchor doesn't work properly).

**Comment by jorangreef** [comment]
Heavy plus one.

**Comment by jorangreef** [comment]
Also:
* Don't grind the browser to a halt for large 100+ commit PRs. 😛 

I don't know if Gitlab helps with any of this.

But how is Fossil for this?

**Comment by jamii** [comment]
I don't think fossils tools can be used on git repos.

There are a bunch of code review tools that work on top of github. I haven't tried any of them before though, so no idea which to recommend.

**Comment by jamii** [comment]
Extra wishlist:

7. Update conversations in real-time so I don't constantly have comment skew (github only updates comments when the page is refreshed).

**Comment by jamii** [comment]
reviewable.io hits 2 and 3. Sort of 4 (has an expand-all in easy reach) and sort of 5 (by virtue of not having a conversation view, instead there's a next/prev comment button in the patch view). Not 1 or 6. Not sure about 7.

It is very good at tracking what you have marked read vs unread. Eg if you mark a commit as seen and then force-push a new version of the commit, it will only show you the new changes as unread.

Doesn't have syntax highlighting for zig.

**Comment by matklad** [comment]
Not that it's actionable, but Jane street's iron workflow is something I've wanted forever. In particular, "review comments are just comments in the code" bit. 

* https://blog.janestreet.com/putting-the-i-back-in-ide-towards-a-github-explorer/
* https://github.com/janestreet/iron

**Comment by jamii** [comment]
:+1: 

I interned there a long time ago and it's still the best code review workflow I've tried.

**Comment by matklad** [comment]
Let's stick with GitHub for now: it's very bad, but I don't immediately know a strictly better alterative. Gerrit might be nice, but Gerrit wants to own the repository and implement not-rockert-scienterules. 

My current prediction is that `jj` folks will come up with some better solution for doing stacked PRs with GitHub as a storage, so let's just wait for now.
