### ISSUE TITLE
Solve `version_check.sh` problem

### ISSUE THREAD

**Issue by matklad** [tigerbeetle/tigerbeetle#389]
https://github.com/tigerbeetledb/tigerbeetle/pull/388 commented out verson_check.sh invocations from the CI. 

That's obviously not a great steady state to be in, we need to do _something_ about it. 

My reading of the code is that version_check essentially enforces the invariant that npm package is always equal to git main. This... doesn't seem to be a too useful property to be honest. I suggest the following:

* just remove version check and related CI checks
* __keep__ the current logic of 'if there isn't a package published with the version, publish it'
* for the time being, rely on "manually update version in package.json once in a while" workflow to get stuff to npm
* at some point in the future, implement automated nightly/weekly publishing of a specially tagged pre-release version to npm

---

The perfect solution here would probably be "npm contains real careful releases, and everyone else can use a version of package from githbub". Sadly, npm, unlike Cargo, dosen't sufficiently support github dependencies to make this work (it requires package.json to be at the root. There are 3rd party servicies which don't, but then they don't work with our not-in-the-least hacky symlink setup)

Another interesting thing to consider is to publist a package as github actions artifact.

**Comment by cb22** [comment]
@matklad do you consider this fixed now with the current setup?

CI checks if the version in `package.json` exists. If it doesn't, it's published as is. If it does exist, it fetches the latest version from npm, increments the patch version, and publishes that instead. 

(This will need to be further refined once we have stable releases!)

**Comment by matklad** [comment]
Was definietly fixed with transition to the new release infra. `run_number` here is now the single source of truth for all versioning information, for the database proper as well as for client libs:

https://github.com/tigerbeetle/tigerbeetle/blob/79efc96786871a1d28c40ef43d4bade2808bf79d/.github/workflows/release.yml#L48
