### ISSUE TITLE
Continuous fuzzing

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#406]
Currently the vopr machine is disabled because the vopr has too many known failures caused by state transfer not being implemented yet. But we have lots of other fuzzers that don't have known failures, are too slow to run in CI and have sometimes regressed. So:

* Extend the vopr hub to switch between any of the fuzzers available, not just the vopr. 
* Comment out the vopr and any fuzzers with known failures.
* Reenable the vopr machine.

**Comment by matklad** [comment]
Done: https://tigerbeetle.github.io/tigerbeetle/
