### ISSUE TITLE
The grid block swap on grid.write_block is not always immediate.

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#419]
When there are write_iops available, the block passed to write_block is immediately replaced by a fresh block. When there are not write_iops available, the block is not replaced until the write is popped from the queue. This seems likely to cause bugs.

**Comment by jamii** [comment]
The first idea that comes to mind is to change the api:
* In the caller, store `?BlockPtr` instead of `BlockPtr`.
* On `grid.write_block` set the block to null and store original pointer it in the write iop or write queue.
* On callback, pass the fresh block as an argument so that it's explicit in the calling code that a new block is replacing the old one.

**Comment by matklad** [comment]
Our plan here is to switch to ref-counted blocks
