### ISSUE TITLE
Measure test/fuzzing coverage

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#493]
Measure at least branch coverage (and aim for at minimum 100% coverage of catch branches in CI).

Possibly also some kind of state space coverage to measure the efficiency of fuzzing, although this is much harder to define.

**Comment by matklad** [comment]
Just to throw an idea here, one thing I occasionally use is _explicit_ coverage marks which works by manually instrumenting the code: 

https://docs.rs/cov-mark/latest/cov_mark/

**Comment by jorangreef** [comment]
@sentientwaffle and I have chatted about leveraging all our existing log statements to track explicit coverage. For example, we have debug logs in most branches already in `replica.zig` and should aim to do the same for LSM. The nice thing with this is then the coverage sites have human readable descriptions given the log messages.

**Comment by matklad** [comment]
https://tigerbeetle.github.io/tigerbeetle/coverage/index.html
