### ISSUE TITLE
Network-topology independent consensus configuration

### ISSUE THREAD

**Issue by matklad** [tigerbeetle/tigerbeetle#529]
At the moment, our network topology leaks into consensus. The user passes the list of addresses on the command line when starting the replica, and the length of that list determines the quorum. That has the following problems: 

* Operator errors can be devastating: making an error when starting a node (as opposed to formating the data file) can lead to data loss
* Not enough flexibility --- we want things like "a cluster is identified by a DNS record which holds superset of replica IPs"

To fix this, we need to do two things:

* persist configuration (just the replcia_count at the moment) into the superblock  (idea for the cli: `--replica 1/6`, first out of six). 
* change MessageBus such that it doesn't assume that nth replcia is nth IP.

**Comment by sentientwaffle** [comment]
What if we separated these?

`--addresses` is a pool of _at least_ `replica_count + standby_count` addresses (but there can be more).
`--listen` is a single address/port for the replica itself to listen on.

`--addresses` are in no particular order — the address:replica mapping is determined by the `header.replica` of the first message received. Eventually when we support dns, `addresses` can be one or more dns record, each of which can correspond to one or more addresses.

(And we could add in a unique identifier in the replica's data file when it is formatted to guard against multiple replicas sharing the same index).

**Comment by matklad** [comment]
Yeah, that’s roughly the plan we discussed on the serverless meeting today!

**Comment by jorangreef** [comment]
> At the moment, our network topology leaks into consensus.

@matklad great insight—gets to the heart of it.

> --addresses is a pool of at least 

@sentientwaffle great proposal overall. Also for the SuperBlock to know the replica's identity (and cluster quorum size).

I think we could allow `--addresses` to be less than `replica_count + standby_count`, provided all replicas share some "superhub" address that they can gossip through.

**Comment by matklad** [comment]
from chat with joran:

If we don't say that `i`th address is the `i`th replica, we need either:

- an explicit handshake message on connection
- a "broadcast" API for message bus to send the initial ping without knowing recepients

Adding a "broadcast" capability to a MessageBus seems like a good idea for a different reason -- some message busses might support native broadcast/multicast capabilities.

**Comment by matklad** [comment]
Closed by this pair of PRs:

* https://github.com/tigerbeetledb/tigerbeetle/pull/546
* https://github.com/tigerbeetledb/tigerbeetle/pull/554

If the operator messes up the order/quantity of IPs, they:

* can't cause a data loss
* would get a bunch of errors in the log about misconfiguration

We still require to pass IPs in the correct order, but fixing _that_ adds a bunch of complexity, which seems rather fundamental!
