### ISSUE TITLE
Gap after checkpoint

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#558]
Under heavy load there is a gap after every checkpoint where the server is just waiting on the network.

![image](https://user-images.githubusercontent.com/340884/224125293-9d28aef2-1fb2-4501-800f-a5f1aae7d2ce.png)

@sentientwaffle commented:

> During a checkpoint, not only can we not commit, but we also don't accept requests/prepares. So we start the new wrap with an empty pipeline. And worse, the clients probably start to back off during the checkpoint.

**Comment by matklad** [comment]
Fixed, checkpoints are semi-async now
