### ISSUE TITLE
[Feature Request] Multimaster cluster

### ISSUE THREAD

**Issue by joeky888** [tigerbeetle/tigerbeetle#599]
Not only performant, developers should also set up a HA cluster like 3 Master and 6 Slaves, which maintains a Strong consistency relationship between Masters and Eventual consistency between Master and Slave. Is it possible to set up right now or on the roadmap?

**Comment by sentientwaffle** [comment]
Hi @joeky888!

We don't plan to support multi-master.
Our existing architecture is highly available though — if the primary fails, another replica will automatically take over.
All writes, and all reads ([tbd](https://github.com/tigerbeetledb/tigerbeetle/pull/593/)) are serialized through the commit log.

We do have (WIP) "standbys", which are replicas that do not participate in consensus, but which nevertheless asynchronously catch up to the cluster (eventual consistency). When they catch up, they can be converted to regular replicas via reconfiguration. (The main use case for this is adding/removing servers from the cluster).

Can you clarify what specific feature you are interested in?

**Comment by joeky888** [comment]
KeyDB, TiDB, CockroachDB and YugabyteDB all have multi-master mode with CDC-driven design afaik. Imaging there are several heavy computations on the hot data of single-master node and the master just that couldn't scale vertically anymore. I believe that's one of the reason that people switched from Redis to KeyDB or switched from MySQL to TiDB.

**Comment by joeky888** [comment]
What we would expect in the production environment are

* A Kubernetes helm chart to set up a multi-master cluster with ease
* Monitoring and alerting system
* Scaling up horizontally without downtime

**Comment by sentientwaffle** [comment]
Yeah, TB is not horizontally scalable. But it will support very high + reliable throughput, so it probably won't be a bottleneck.

For very expensive/complex queries, you would want to handle that outside of TB — for that we will support a CDC export stream, so you could ship the accounts/transfers to another database (e.g. for analytics).

**Comment by sebalvarado** [comment]
Hi @sentientwaffle are you guys already supporting the CDC export stream? We are evaluating TB for our banking core application and want to build reporting functions on top of the core ledger transactions and accounts recorded on TB.

**Comment by RealZimboGuy** [comment]
> Yeah, TB is not horizontally scalable. But it will support very high + reliable throughput, so it probably won't be a bottleneck.
> 
> For very expensive/complex queries, you would want to handle that outside of TB — for that we will support a CDC export stream, so you could ship the accounts/transfers to another database (e.g. for analytics).

i second the CDC stream question, for things like EOD processing ie merchant settlement and calculations of merchant commissions it is quite important to be able to post process and sweep commissions

**Comment by sentientwaffle** [comment]
CDC isn't implemented yet, but we do have progress here: The underlying LSM query primitives are implemented (to support querying transfers for an account -- https://docs.tigerbeetle.com/reference/operations/get_account_transfers).

(We are working to get TB production-ready in the near future, and implementing CDC will be a high priority after that -- TB's data layout is very well-suited to it!)
