### ISSUE TITLE
with iran ip, website respond `406 Not Acceptable`

### ISSUE THREAD

**Issue by alichraghi** [tigerbeetle/tigerbeetle#65]
when i open [tigerbeetle.com](https://www.tigerbeetle.com) with iran ip it respond with 406 code. loads correctly when i use VPN
![image](https://user-images.githubusercontent.com/63465728/145777337-25104a78-5908-44ca-bfd6-2b997c580f26.png)

**Comment by jorangreef** [comment]
Thanks @AliChraghi yes we are aware of the issue. I think it's upstream with our website host.
