### ISSUE TITLE
MessageBus: Optimize to receive into header-only messages if possible

### ISSUE THREAD

**Issue by jorangreef** [tigerbeetle/tigerbeetle#70]
We do have a separate pool containing many more `message_bus_headers_max` messages in addition to the full-sized messages in `message_bus_messages_max` but `MessageBus` is using up a whole full-sized message for the incoming `prepare_ok` messages.

We should optimize this in `MessageBus`, so that if the `header.size` is exactly `@sizeOf(Header)` then we copy the header into a header-only message, and unref the full message.

This would make it less likely that the `MessageBus` would run out of full-sized messages. It also means we can reduce our memory overhead by reducing the duration for which we hold onto full messages that we `recv` into at the TCP layer. i.e. Our pool becomes more just-in-time, for less message "inventory holding costs".

**Comment by sentientwaffle** [comment]
Closing; static message pool capacity (https://github.com/coilhq/tigerbeetle/pull/72) is incompatible with header-only messages.

Details: https://github.com/coilhq/tigerbeetle/pull/72#issuecomment-1022606287.
