### ISSUE TITLE
MessageBus: Only have one logical implementation, refactoring TCP out into swappable Network

### ISSUE THREAD

**Issue by jorangreef** [tigerbeetle/tigerbeetle#71]
If we fix #70 then we need to do the same in `Network.deliver_message` to match this logic.

But this is a sign that we actually need to refactor `MessageBus` a little so that it accepts a swappable `Network` which does the TCP connection stuff that `MessageBus.Connection` currently does.

The goal of this refactor would be to get rid of `test/message_bus.zig` completely and make sure that we’re testing the exact same message bus logic.

@ifreund  what are your thoughts on this?

**Comment by sentientwaffle** [comment]
Is this still applicable, since there is no header-only message pool anymore, and the message pool isn't owned by the `MessageBus`? I don't see much (if any) shared logic between the primary & test `MessageBus` implementations.

**Comment by jorangreef** [comment]
If there's no longer any shared logic at all between primary and test implementations, then let's close!
