### ISSUE TITLE
Client: Don't panic on evict

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#781]
Important for two reasons:
- Makes client eviction testable in `replica_test.zig` and the simulator.
- Allows (language) clients to reconnect with a new session if they so choose.

**Comment by kris-hansen** [comment]
I agree with not panic-ing in general, but what would be the desired behaviour here? Evict the client session / not panic the thread / keep the thread open for retry / timeout the thread if retry is not attempted? 

I would worry about a potential situation where too many threads are opened and not getting the resources harvested in time and creating a bad situation.

**Comment by sentientwaffle** [comment]
I'm not sure! It probably depends somewhat on the language in question, too.

**Comment by sentientwaffle** [comment]
Fixed by https://github.com/tigerbeetle/tigerbeetle/pull/2484
