### ISSUE TITLE
C client header - need C & C++ compatibility

### ISSUE THREAD

**Issue by kassane** [tigerbeetle/tigerbeetle#788]
Suggestion: add `extern "C"` on `tb_client.h`.

Given error:
```bash
[build] [ 80%] Linking CXX executable tb_cpp
[build] ld.lld: error: undefined symbol: tb_client_submit(void*, tb_packet_list_t*)
[build] >>> referenced by tb_client.hpp:106 (/home/kassane/Documents/tb-client-cpp/include/tb_client.hpp:106)
[build] >>>               CMakeFiles/tb_cpp.dir/src/main.cpp.o:(tb::Client::send_request(void*, tb_packet_list_t*, tb::CompletionContext*))
[build] >>> did you mean: extern "C" tb_client_submit
[build] >>> defined in: /home/kassane/Documents/tb-client-cpp/vendor/lib/libtb_client.so
[build] make[2]: *** [CMakeFiles/tb_cpp.dir/build.make:99: tb_cpp] Error 1
[build] make[1]: *** [CMakeFiles/Makefile2:99: CMakeFiles/tb_cpp.dir/all] Error 2
[build] make: *** [Makefile:136: all] Error 2
[proc] The command: /usr/bin/cmake --build /home/kassane/Documents/tb-client-cpp/build --config Debug --target all -j 18 -- exited with code: 2
[driver] Build completed: 00:00:00.167
[build] Build finished with exit code 2
```

**Comment by eatonphil** [comment]
Hey there! Nice report! What do you think @batiati?

**Comment by batiati** [comment]
Hi @kassane!
That's a good suggestion, in the meantime, you can just surround your include with `extern "C"` that would work too.

```c++
extern "C" {
#include "tb_client.h"
}
```

Btw, what are you up to with this `tb-client-cpp` 😎 🔥🔥🔥

**Comment by kassane** [comment]
> That's a good suggestion, in the meantime, you can just surround your include with `extern "C"` that would work too.
> 
> ```c++
> extern "C" {
> #include "tb_client.h"
> }
> ```

Exactly!
During local testing I changed `tb_client.h` and after that it worked.

However, that way, it would have its own version of the header that could cause problems in future updates.

Currently, I use CMake to download dependencies, including Tigerbeetle to get the tb_client header file.

> 
> Btw, what are you up to with this `tb-client-cpp` 😎 🔥🔥🔥
> 

I'm starting to replicate the example already available in c_sample.
It will involve a cross-platform solution.
Any contributions are welcome!!

WiP:
https://github.com/kassane/tb-client-cpp
