### ISSUE TITLE
Client crashing

### ISSUE THREAD

**Issue by matdehaast** [tigerbeetle/tigerbeetle#88]
Hi TB Team,

So we are running into an issue where the TB client is crashing due to an assert error. @cairin picked this up in our local env

```
tigerbeetle- 0  url: 10.244.0.54:8080
2022/04/11 11:39:59 grpc server: 0.0.0.0:8080
info(message_bus): connected to replica 0
thread 10 panic: reached unreachable code
/home/don/github/coilhq/tigerbeetle/zig/lib/std/debug.zig:226:14: 0x7f8fc1cbf378 in std.debug.assert (client_c)
/home/don/github/fynbos/fynbos/go/tigerbeetle_go/internal/tigerbeetle/src/vsr/client.zig:484:19: 0x7f8fc1cce7d5 in tigerbeetle.src.vsr.client.Client(tigerbeetle.src.state_machine.StateMachine,tigerbeetle.src.message_bus.MessageBusImpl(tigerbeetle.src.message_bus.ProcessType.client)).send_request_for_the_first_time (client_c)
/home/don/github/fynbos/fynbos/go/tigerbeetle_go/internal/tigerbeetle/src/vsr/client.zig:205:64: 0x7f8fc1cc2f38 in tigerbeetle.src.vsr.client.Client(tigerbeetle.src.state_machine.StateMachine,tigerbeetle.src.message_bus.MessageBusImpl(tigerbeetle.src.message_bus.ProcessType.client)).request (client_c)
/home/don/github/fynbos/fynbos/go/tigerbeetle_go/internal/client_c/client_c.zig:189:19: 0x7f8fc1cc2b2f in request (client_c)
```

But not 100% what is going on sure as I don't know the client code well enough but the failure is happening here https://github.com/coilhq/tigerbeetle/blob/bd9f03a7f9bf31c62a20c8864a5cd05a775256ba/src/vsr/client.zig#L484 

Note i've liked a previous commit as our build is from that commit.

This seems to occur when doing quite a few requests quickly.

**Comment by sentientwaffle** [comment]
Is the build of `tigerbeetle_go` you're using accessible anywhere? I don't see `client_c.zig` in any branches of https://github.com/coilhq/tigerbeetle-go/.

**Comment by sentientwaffle** [comment]
Also, can you confirm that TB's client is only ever called from a single thread at a time (e.g. guarded by a mutex)? I assume tigerbeetle-go would do this internally, but I don't think I have access to check.

**Comment by matdehaast** [comment]
@sentientwaffle thanks for looking into it. It is there on the `main` branch
https://github.com/coilhq/tigerbeetle-go/blob/main/internal/client_c/client_c.zig

> Also, can you confirm that TB's client is only ever called from a single thread at a time (e.g. guarded by a mutex)? I assume tigerbeetle-go would do this internally, but I don't think I have access to check.

I don't think it does that at all, from my understanding of the code it just creates an single instance of a tigerbeetle client. We create a singleton of the library but I think that is potentially called from multiple green threads.

**Comment by sentientwaffle** [comment]
> We create a singleton of the library but I think that is potentially called from multiple green threads.

That is probably the issue. The TB client is single-threaded by design. The assertion failure you see looks like a race condition caused by access from multiple threads (in this case, I think the same `Message` is being acquired/modified simultaneously by 2 threads).
