### ISSUE TITLE
Rename grid.alloc_block() to grid.allocate_block()

### ISSUE THREAD

**Issue by jorangreef** [tigerbeetle/tigerbeetle#927]
Per TigerStyle, “Do not abbreviate [...] names” and the reason we use `snake_case`, to encourage more descriptive, complete names.

**Comment by ItIsOHM** [comment]
Hey there, I'd love to work on this issue. But since I'm a beginner it'd be of great help if you could point me from where I can start? I have forked and cloned the repo but couldn't find `grid.alloc_block()`

**Comment by eatonphil** [comment]
Hey @ItIsOHM! Awesome to see your interest! Take a look at src/lsm/grid.zig and follow our https://github.com/tigerbeetledb/tigerbeetle/blob/main/docs/HACKING.md guide to make sure your changes build.

Also, a tip in general is that `git grep X` will show you all the occurrences of `X` in a repo.

Good luck!

**Comment by ItIsOHM** [comment]
@eatonphil thanks for the help! I was going through the `HACKING.md` file, and found out that the current beta only supports MacOS and Linux, but I use Windows 11. And therefore I wanted to ask if it would even be possible for me to build tigerbeetle after making the changes to run the unit tests?

**Comment by eatonphil** [comment]
Ah, we should update that. Yes it should build on Windows as well.

**Comment by ItIsOHM** [comment]
> Ah, we should update that. Yes it should build on Windows as well.

Ah alright! Then i'll start working on it ASAP :)

**Comment by ItIsOHM** [comment]
Hey @eatonphil, I made changes to `grid.zig` as you suggested, but when building it, I'm getting a few errors:
![image](https://github.com/tigerbeetledb/tigerbeetle/assets/62976081/b8618809-5759-4665-97a2-fa34d8f34c1b)

What should my next step be?

**Comment by eatonphil** [comment]
Make sure to follow the directions in HACKING.md. :) You must use the version of Zig we provide from scripts\install_zig.bat.

**Comment by ItIsOHM** [comment]
Hey so I installed the version mentioned in HACKING.md, and ran the test. After successfully running for quite a while it gave me errors: 
![image](https://github.com/tigerbeetledb/tigerbeetle/assets/62976081/64bd2695-79ae-4440-a7ca-0c89d3fac93b)
which says `aof.test "aof write / read"... thread 9484 panic: create_or_open is unsupported on Windows.`

How can I solve this?

**Comment by eatonphil** [comment]
Ah, I know TigerBeetle builds on Windows but I am not sure if the tests normally full run.

It may be best then if you do the testing within a VirtualBox VM or a Docker container, basically, some Linux environment.

**Comment by ItIsOHM** [comment]
> Ah, I know TigerBeetle builds on Windows but I am not sure if the tests normally full run.
> 
> It may be best then if you do the testing within a VirtualBox VM or a Docker container, basically, some Linux environment.

Oh I see, unfortunately I'm not familiar with either VirtualBox or Docker, and so I don't think I'd be able to work well in a Linux env. Do you suggest I should drop this issue as of now?

**Comment by eatonphil** [comment]
@ItIsOHM actually in this case I think if you just make sure `zig\zig.exe build` works then I think it will be sufficient.

**Comment by ItIsOHM** [comment]
> @ItIsOHM actually in this case I think if you just make sure `zig\zig.exe build` works then I think it will be sufficient.

Hey there, it looks like `zig.exe build` worked!
It did some semantic analysis and a bunch of other things, and eventually it looks like it succeeded since it didn't return any errors. A new folder named `zig-out` was also which I think contains the executables to run Tigerbeetle.

Let me know and i'll open a PR :D

**Comment by eatonphil** [comment]
Sounds ok from what you've said. Open the PR and we'll see!

**Comment by ItIsOHM** [comment]
> Sounds ok from what you've said. Open the PR and we'll see!

So, I opened a PR with the necessary changes, but accidentally synced it with the main tigerbeetle branch after pulling so had close that PR. I'll make the changes again and open a new PR ASAP :)

**Comment by ItIsOHM** [comment]
Hey @eatonphil just opened a PR with commits that might fix this issue (https://github.com/tigerbeetledb/tigerbeetle/pull/941)

Also let me know if I made any mistakes, I'm just a beginner here :)
