### ISSUE TITLE
Add sample project to language clients that shows multiple two-phase transfers in flight all at once

### ISSUE THREAD

**Issue by eatonphil** [tigerbeetle/tigerbeetle#943]
See https://tigerbeetle.slack.com/archives/C04375JUAMS/p1688158327999759 for background.

- [x] Go client #1051
- [x] Java client https://github.com/tigerbeetle/tigerbeetle/pull/1156
- [x] Dotnet client https://github.com/tigerbeetle/tigerbeetle/pull/1153
- [x] Node client https://github.com/tigerbeetle/tigerbeetle/pull/1147

**Comment by jamalzkhan** [comment]
👍

**Comment by eatonphil** [comment]
This should follow the same structure as the existing sample projects and use only a single file for simplicity.

We should probably have it create two accounts and send 5 pending transfers and have 4 be marked as completed and 1 marked as void.

In the future two of them should be allowed to timeout but we haven't implemented two-phase transfer timeouts yet so that wouldn't work yet.

All the while we should make assertions about account balances like we do in the existing two-phase transfer project.
